### ISSUE TITLE
yaml-cpp on VS2019

### ISSUE THREAD

**Issue by SylvainArd** [jbeder/yaml-cpp#1000]
Hello !
is there a version of yaml-cpp for Visual Studio 2019 please ?
thank you !
best regards

**Comment by jbeder** [comment]
You can generate any project file you like with cmake. Please see https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2016%202019.html

**Comment by SylvainArd** [comment]
no it doesn't works because the source code is for VS2015 and not VS2019 ! I tried and got a lot of errors but it compiles with VS2015
