### ISSUE TITLE
Node raw pointer / C API support 

### ISSUE THREAD

**Issue by ksiero** [jbeder/yaml-cpp#1002]
Hi,
I wanted to write a simple C wrapper, but I have a problem with memory allocation. I have to store each accessed Node , this adds unnecessary memory overhead.

What I need in my wrapper is just a root Node (shared pointer to keep a memory alive) and raw pointer to accessed nodes.
I can see that there is already raw pointer to the node in: https://github.com/jbeder/yaml-cpp/blob/a6bbe0e50ac4074f0b9b44188c28cf00caf1a723/include/yaml-cpp/node/node.h#L137

But it is private. Is there an option to make a getter for this raw pointer? Does this class has some API stability insurance?

Or maybe event better is C API support planned?

**Comment by jbeder** [comment]
If you just want a C API, there's a good one here:

https://github.com/yaml/libyaml
