### ISSUE TITLE
std::wstring support

### ISSUE THREAD

**Issue by muaddib1971** [jbeder/yaml-cpp#1013]
Hi There 

Are wide character conversions supported in yaml-cpp? 

I'm trying to convert my project over to using unicode as I want to store and display some graphics characters not supported by asci.

I am getting the following compiler error and I'm not sure if I'm causing it or it's in your code base: 

/home/muaddib/git/boardmaker/src/../yaml-cpp/include/yaml-cpp/node/impl.h: In instantiation of ‘T YAML::as_if<T, void>::operator()() const [with T = std::__cxx11::basic_string<wchar_t>]’:
/home/muaddib/git/boardmaker/src/../yaml-cpp/include/yaml-cpp/node/impl.h:156:31:   required from ‘T YAML::Node::as() const [with T = std::__cxx11::basic_string<wchar_t>]’
/home/muaddib/git/boardmaker/src/boardmaker/view/view.cpp:44:57:   required from here
/home/muaddib/git/boardmaker/src/../yaml-cpp/include/yaml-cpp/node/impl.h:131:27: error: incomplete type ‘YAML::convert<std::__cxx11::basic_string<wchar_t> >’ used in nested name specifier
     if (convert<T>::decode(node, t))
         ~~~~~~~~~~~~~~~~~~^~~~~~~~~

The code had been working fine up till now using std::string but it's having trouble with std::wstring. 

thanks

**Comment by jbeder** [comment]
Not natively, no; all strings are represented as utf8 with `std::string`. If you want `std::wstring`, you'll have to translate to whatever wide encoding you want.
