### ISSUE TITLE
enable static linking of yaml-cpp

### ISSUE THREAD

**Issue by christian-rauch** [jbeder/yaml-cpp#1031]
Querying the static yaml-cpp libraries via
```bash
pkg-config --libs --static yaml-cpp
```
provides the same linking flags as for the shared library:
```
-L/usr//usr/lib/x86_64-linux-gnu -lyaml-cpp
```
whereas it should provide the static library `-lyaml-cpp.a`.

For CMake, you could adapt the solution from: https://gitlab.inria.fr/Puffertools/pufferscaletest/pufferscale-exp/blob/master/cmake/Modules/FindYamlCpp.cmake which lets one set `YAMLCPP_USE_STATIC_LIBS` before searching the library.

**Comment by gelldur** [comment]
I build it like this:

```
###############################################################################
TYPE=Release
INSTALL=${BUILD_DIR}/install-${TYPE}
BUILD=build-${TYPE}
echo "Building: $BUILD <-------------------------------------------------------"
(cd ${BUILD_DIR} && rm -rf $BUILD && mkdir -p $BUILD) || exit 1
(cd ${BUILD_DIR}/$BUILD && cmake ${DIR}/../yaml-cpp \
	-DBUILD_SHARED_LIBS=OFF \
	-DYAML_BUILD_SHARED_LIBS=OFF \
	-DBUILD_TESTING=OFF \
	-DCMAKE_BUILD_TYPE=${TYPE} \
	-DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang \
	-DCMAKE_INSTALL_PREFIX=${INSTALL}) || exit 1
(cd ${BUILD_DIR}/$BUILD && cmake --build . --target install -j 8) || exit 1
(cd ${BUILD_DIR} && rm -rf $BUILD) # Cleanup
###############################################################################

###############################################################################
TYPE=Debug
INSTALL=${BUILD_DIR}/install-${TYPE}
BUILD=build-${TYPE}
echo "Building: $BUILD <-------------------------------------------------------"
(cd ${BUILD_DIR} && rm -rf $BUILD && mkdir -p $BUILD) || exit 1
(cd ${BUILD_DIR}/$BUILD && cmake ${DIR}/../yaml-cpp \
	-DBUILD_SHARED_LIBS=ON \
	-DYAML_BUILD_SHARED_LIBS=ON \
	-DBUILD_TESTING=OFF \
	-DCMAKE_BUILD_TYPE=${TYPE} \
	-DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang \
	-DCMAKE_INSTALL_PREFIX=${INSTALL}) || exit 1
(cd ${BUILD_DIR}/$BUILD && cmake --build . --target install -j 8) || exit 1
(cd ${BUILD_DIR} && rm -rf $BUILD) # Cleanup
###############################################################################
```

In debug I get `.so` in release I have `.a`

**Comment by christian-rauch** [comment]
Sure, the documentation mentions `YAML_BUILD_SHARED_LIBS` to build the static libs. But with two separate compile runs, you generate two separate configurations.

The point I am making with the pkg-config is that it should be possible to build shared and static libraries in parallel, such that once installed, you can query either the shared or static lib via pkg-config. The `libyaml-cpp` packages in distributions already provide shared and static libs (`libyaml-cpp.so.0.6`, `libyaml-cpp.a`). But the pkg-config does not allow you to query the static lib (`*.a`), only the shared lib (`*.so`).

**Comment by christian-rauch** [comment]
Setting `YAML_BUILD_SHARED_LIBS=OFF` should also automatically enable PIC (`CMAKE_POSITION_INDEPENDENT_CODE=ON`).

**Comment by jbeder** [comment]
This is reasonable. I'd accept a PR.

**Comment by christian-rauch** [comment]
> This is reasonable. I'd accept a PR.

https://github.com/jbeder/yaml-cpp/pull/1076
