### ISSUE TITLE
YAML::LoadFile() does not work (?)

### ISSUE THREAD

**Issue by gzagaris** [jbeder/yaml-cpp#1041]
Any apparent reason why the following does not work?
```
YAML::Node data;
  data[ "constants" ][ "foo" ] = 42;

  std::ofstream ofs( "data.yaml" );
  ofs << data;
  std::cout << "INPUT DATA:" << std::endl;
  std::cout << data << std::endl << std::endl;


  YAML::Node test_data = YAML::LoadFile( "./data.yaml" );
  std::cout << "DATA FROM FILE:" << std::endl;
  std::cout << test_data << std::endl << std::endl;
```

**Comment by sei-mwd** [comment]
This happens because the data written to `ofs` hasn't been flushed by the time you are reading its file's data.  You can flush it with `ofs.flush()` or by closing the file by either calling `ofs.close()` or by allowing `ofs` to go out of scope.

**Comment by gzagaris** [comment]
oh! yes, of course! Thanks, @sei-mwd!
