### ISSUE TITLE
YAML::LoadFile() throw execption: string too long

### ISSUE THREAD

**Issue by yuzifu** [jbeder/yaml-cpp#1060]
I have a yaml file config.yml, the content as follow:
```
timeout: 10
```

The read yaml source code is as follows:
```
#include "yaml-cpp/yaml.h"

try
{
	auto yCfg = YAML::LoadFile("config.yml");
}
catch (exception& e)
{
	// string too long
	return;
}
```

I searched the code repo and couldn't find this keyword.

How do I fix this error?

**Comment by WYZ1780** [comment]
你好 ，我最近也在Windows平台上遇到了这个问题，请问您是怎么解决的？
