### ISSUE TITLE
Hex string becomes hex literal when using LoadFile

### ISSUE THREAD

**Issue by kilicbaran** [jbeder/yaml-cpp#1065]
Let's say, I have a file like this:
```yaml
- '0x0000000000000000000000000000000000000000'
- '0x0000000000000000000000000000000000000001'
```
When I read this file and emit the yaml as string like this:
```cpp
YAML::Emitter out;
out << YAML::LoadFile("file.yaml");
std::cout << out.c_str();
```
the yaml becomes like this (the values are no more string):
```
- 0x0000000000000000000000000000000000000000
- 0x0000000000000000000000000000000000000001
```
 Do I use the library in a wrong way? Is this a bug?

**Comment by jbeder** [comment]
yaml-cop doesn’t remember that it was a string when emitting. You could
check it explicitly (it’s in the data representation) but. It used when
emitting.

**Comment by kilicbaran** [comment]
Thanks for the quick response. I asked this because I noticed that the YAML parsers for other programming languages behave differently and this confused me. When I try to output 0x0 as a string (not as a number), they enclose it with quotes. I think it is related to the tag resolution. The values that match this regular expression `0x [0-9a-fA-F]+` are interpreted as `tag:yaml.org,2002:int`. Therefore, they enclose the value with quotes so that it is interpreted as string.

**Comment by perlpunk** [comment]
If yaml-cpp implements the 1.2 Core schema (see https://perlpunk.github.io/yaml-test-schema/schemas.html) then it indeed must quote a string like `0x123` because otherwise it will be loaded as a number next time it is loaded.

**Comment by jbeder** [comment]
Yeah this is probably right, it’s a bug.
