### ISSUE TITLE
BUILD_SHARED_LIBS=yes stopped working

### ISSUE THREAD

**Issue by md5i** [jbeder/yaml-cpp#1066]
Compiling with `-DBUILD_SHARED_LIBS=yes` has stopped working.  It stopped working in commit 0733aeb451e2526dc05824d954348ca5baa0feed.  

There are two workarounds that work for my purposes: `-DYAML_BUILD_SHARED_LIBS=yes` works; `-DYAML_CPP_BUILD_TEST=no` works.  This means that this problem is not a blocker for me, but I figured that I should report it anyway.

The error is caused when linking the gmock test program.

Partial output follows:

```
...
[ 53%] Linking CXX shared library libyaml-cpp.so
[ 53%] Built target yaml-cpp
Scanning dependencies of target gtest
[ 55%] Building CXX object test/prefix/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 56%] Linking CXX shared library ../../../lib/libgtest.so
[ 56%] Built target gtest
Scanning dependencies of target gmock
[ 58%] Building CXX object test/prefix/googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
[ 60%] Linking CXX shared library ../../../lib/libgmock.so
[ 60%] Built target gmock
Scanning dependencies of target yaml-cpp-tests
[ 61%] Building CXX object test/CMakeFiles/yaml-cpp-tests.dir/integration/emitter_test.cpp.o
[ 63%] Building CXX object test/CMakeFiles/yaml-cpp-tests.dir/integration/encoding_test.cpp.o
[ 65%] Building CXX object test/CMakeFiles/yaml-cpp-tests.dir/integration/error_messages_test.cpp.o
[ 66%] Building CXX object test/CMakeFiles/yaml-cpp-tests.dir/integration/gen_emitter_test.cpp.o
[ 68%] Building CXX object test/CMakeFiles/yaml-cpp-tests.dir/integration/handler_spec_test.cpp.o
[ 70%] Building CXX object test/CMakeFiles/yaml-cpp-tests.dir/integration/handler_test.cpp.o
[ 71%] Building CXX object test/CMakeFiles/yaml-cpp-tests.dir/integration/load_node_test.cpp.o
[ 73%] Building CXX object test/CMakeFiles/yaml-cpp-tests.dir/integration/node_spec_test.cpp.o
[ 75%] Building CXX object test/CMakeFiles/yaml-cpp-tests.dir/main.cpp.o
[ 76%] Building CXX object test/CMakeFiles/yaml-cpp-tests.dir/node/node_test.cpp.o
[ 78%] Building CXX object test/CMakeFiles/yaml-cpp-tests.dir/ostream_wrapper_test.cpp.o
[ 80%] Building CXX object test/CMakeFiles/yaml-cpp-tests.dir/parser_test.cpp.o
[ 81%] Building CXX object test/CMakeFiles/yaml-cpp-tests.dir/regex_test.cpp.o
[ 83%] Linking CXX executable yaml-cpp-tests
../lib/libgmock.so: undefined reference to `testing::internal::ParseInt32(testing::Message const&, char const*, int*)'
collect2: error: ld returned 1 exit status
make[2]: *** [test/CMakeFiles/yaml-cpp-tests.dir/build.make:287: test/yaml-cpp-tests] Error 1
make[1]: *** [CMakeFiles/Makefile2:1044: test/CMakeFiles/yaml-cpp-tests.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
```

**Comment by jbeder** [comment]
This is likely fixed by 2b65c65e1be6f2eec7a1ad6a91bc5a8765a7e4bd; can you verify?

But also: do you expect `-DBUILD_SHARED_LIBS=yes` to work out of the box, rather than `-DYAML_BUILD_SHARED_LIBS=yes`? I'm not a CMake expert, so I just mostly approve whatever people tell me, but right now all that's tested is `-DYAML_BUILD_SHARED_LIBS=yes` (see [here][action-shared]). If you want `-DBUILD_SHARED_LIBS=yes` to work, could you submit a PR that adds a test for it?

[action-shared]: https://github.com/jbeder/yaml-cpp/blob/master/.github/workflows/build.yml#L32

**Comment by md5i** [comment]
Thank you.  I can confirm that it is fixed.

I currently build with `-DBUILD_SHARED_LIBS=yes -DYAML_BUILD_SHARED_LIBS=yes`.  This is because both of these were necessary in an older version of yaml-cpp.  I'm trying to build with a set of options that will work with both current and older versions of the yaml-cpp sources.  Other than that (backwards compatibility), I would normally prefer just using `-DYAML_BUILD_SHARED_LIBS=yes`.

**Comment by jbeder** [comment]
Thanks for the update. I think we'll just keep the
-DYAML_BUILD_SHARED_LIBS=yes as what's officially supported, based on what
you said.
