### ISSUE TITLE
security alerts

### ISSUE THREAD

**Issue by mcandre** [jbeder/yaml-cpp#1096]
Hi,

Snyk reports multiple security alerts for yaml-cpp code:

https://security.snyk.io/vuln?search=jbeder%2Fyaml-cpp

When can we expect a new release with the vulnerabilities resolved?

**Comment by jbeder** [comment]
When people submit PRs to address those issues.

**Comment by mcandre** [comment]
Why have the GitHub issues been closed? Your package is chock full of CVE's left unpatched.

**Comment by jbeder** [comment]
I close issues when I think the issue is resolved. If I'm wrong (which I'm sure happens) please comment politely on the relevant issue with an explanation of how the tagged PR doesn't resolve the issue, and I'll reopen the issue. I certainly don't intend to close bugs that are unresolved.
