### ISSUE TITLE
Does it support to parse a YAML file which includes another YAML file inside?

### ISSUE THREAD

**Issue by ken1119900** [jbeder/yaml-cpp#1097]
Hi,  

I know that "include" or "import" seems not a native YAML syntax.  But some yaml parser like PyYAML could support this syntax.

I do some search on this usage of this tool but not find related information.  I also try to use simple case to try but get below error.  _"terminate called after throwing an instance of 'YAML::BadSubscript'"_
yaml content:
**test: !include test.yml**

Is this tool able to parse a YAML file which includes another YAML file inside?  If no, is there a suggested way to parse this kind of yaml for now?

Reference: https://stackoverflow.com/questions/528281/how-can-i-include-a-yaml-file-inside-another

Thanks,
Ken

**Comment by jbeder** [comment]
No, yaml-cpp doesn't support including another YAML file; you'd have to write some code manually.
