### ISSUE TITLE
Is it possible to write certain arrays in a single line form?

### ISSUE THREAD

**Issue by GasimGasimzada** [jbeder/yaml-cpp#1123]
I am generating a YAML file using this library and I write arrays in the following way:

```cpp
template <> struct convert<glm::vec3> {
  static Node encode(const glm::vec3 &value) {
    Node node;
    node.push_back(value.x);
    node.push_back(value.y);
    node.push_back(value.z);
    return node;
  }

  static bool decode(const Node &node, glm::vec3 &value) {
    if (!node.IsSequence() || node.size() != 3) {
      return false;
    }

    value.x = node[0].as<float>();
    value.y = node[1].as<float>();
    value.z = node[2].as<float>();
    return true;
  }
};

YAML::Node node;
node["position"] = transform.position; // glm::vec3
```

This generates YAML file in the following way:

```yaml
position:
  - 10.5
  - 0.5
  - -2.5
```

Is it possible to tell YAML to ONLY treat this type as a single line array:

```yaml
position: [10.5, 0.5, -2.5]
```

I know that they both represent the same thing but from human readability perspective, I want to treat write "tuple" type objects in a single line. Is there a configuration to do that? If not, is there a configuration that I can set, which writes arrays as single line if number of items is less than X?

**Comment by jbeder** [comment]
Not exactly; if you're using the `Emitter` API for each piece, you can use `YAML::Flow` on just the part you want. But if you're trying to write the whole node at once, you can't specify flow for some parts and block for others.
