### ISSUE TITLE
YAML_CPP issue using XCode: Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by dbl001** [jbeder/yaml-cpp#1129]
Do you have an suggestions on this issue building 'SuperCollider'?
I posted the question on StackOverflow, but didn't get any response.
See details here ...
https://stackoverflow.com/questions/73533092/yaml-cpp-issue-using-xcode-undefined-symbols-for-architecture-x86-64

**Comment by jbeder** [comment]
Maybe ask the SuperCollider team?

**Comment by dbl001** [comment]
I did ... 

https://github.com/supercollider/supercollider/issues/5852

**Comment by jbeder** [comment]
Sorry, I don't think I can be more help than they were here.
