### ISSUE TITLE
Using yaml-cpp as dependency within a project using CMake

### ISSUE THREAD

**Issue by Trompettesib** [jbeder/yaml-cpp#1136]
How am I suppsed to do to integrate yaml-cpp library into my project without having to include all the sources into a directory ?
My objective is that when I build the project, if the yaml-cpp library isn't downloaded yet, CMake will download it and build it.

**Comment by Trompettesib** [comment]
I think the answer for this question is this comment https://github.com/jbeder/yaml-cpp/issues/774#issuecomment-737155168
maybe it would be interesting to put it in the documentation

**Comment by jbeder** [comment]
I’m open to PRs to update documentation.

**Comment by Trompettesib** [comment]
I have created a pull request !
#1143

**Comment by ahogen** [comment]
PR #1143 was merged. This issue can be closed.
