### ISSUE TITLE
Mark() operations return incorrect values

### ISSUE THREAD

**Issue by dipsylala** [jbeder/yaml-cpp#1138]
Hi,
When using Mark() on a set of Nodes, I appear to be getting incorrect values, but I'm keen to see if there is a misunderstanding on my part. 

Testing on version 0.7.0, windows built using `cmake -G "Visual Studio 17 2022"`

Input file:
```
root:
  child-one:
    grandchild-one: false
  child-two:
    grandchild-two: true
```

Test code:
```
int main()
{
    YAML::Node testFile = YAML::LoadFile("test.yaml");

    YAML::Node rootNode = testFile["root"];
    YAML::Node childOneNode = testFile["root"]["child-one"]["grandchild-one"];
    YAML::Node childTwoNode = testFile["root"]["child-two"]["grandchild-two"];

    YAML::Mark rootLineDetails = rootNode.Mark(); // Expected Line 1, column 1. Returns Line 1 column 2
    YAML::Mark oneLineDetails = childOneNode.Mark(); // Expected Line 3, column 5. Returns Line 2 column 20
    YAML::Mark twoLineDetails = childTwoNode.Mark(); // Expected Line 5, column 5. Returns Line 4 column 20
}
```

While the column may be off depending on whether we measure at the ':' or the start of the value, the line number reported refers to the line above (child-one, child-two) rather than the node I'm referencing (grandchild-one, grandchild-two).

Is this expected behaviour?

**Comment by jbeder** [comment]
These values look correct to me. For example, the second one
(testFile["root"]["child-one"]["grandchild-one"]) would have the value of
“false” if you asked it, and the line/column it gives (2/20) is the
location of the text “false”.

**Comment by dipsylala** [comment]
`rootNode.Mark()` returns 1, so I thought a 1-based index though, which was what threw me. `grandchild-one` is on the 3rd line so given a 1-based index it should be 3, not 2?

**Comment by dipsylala** [comment]
I've expanded on the original test to return every line, taking into account ':' being the point representing the column returned.

```
    // Should refer to "root" - Line 1, column 6, Mark() returns Line 1 column 2
    YAML::Mark rootLineDetails = testFile["root"].Mark()

    // Should refer to "child-one" - Line 2, column 13, Mark() returns Line 2 column 4
    YAML::Mark childOneLineDetails = testFile["root"]["child-one"].Mark();

    // Should refer to "grandchild-one"  Expected Line 3, column 20, returns Line 2 column 20
    YAML::Mark granchildOneLineDetails = testFile["root"]["child-one"]["grandchild-one"].Mark(); 

    // Should refer to "child-two" - Line 4, column 13, Mark() returns Line 4, column 4
    YAML::Mark childTwoLineDetails = testFile["root"]["child-two"].Mark();

    // Should refer to "grandchild-two" - Line 5, column 20, Mark() returns Line 4, column 20
    YAML::Mark granchildTwoLineDetails = testFile["root"]["child-two"]["grandchild-two"].Mark();
```

**Comment by jbeder** [comment]
Perhaps the misunderstanding is that

testFile["root"]

is not the root of your document, but rather the value associated with the key "root"?

In other words, it represents a map mode with two key/value pairs, etc, starting on line 1 (zero-based).
