### ISSUE TITLE
Preserving Tags in YAML::Load

### ISSUE THREAD

**Issue by joergbrech** [jbeder/yaml-cpp#1142]
When I `YAML::Load` a node with a local tag, the tag type and tag contents are not preserved.

## Minimal example

I am using the 0.7.0 conan package.

```cpp
auto x = YAML::Node(42);

YAML::Emitter e;
e << YAML::LocalTag("x") << x;
std::string s = e.c_str();
auto y = YAML::Load(s);

std::cout << "before: " << s << std::endl;
std::cout << "tag:    " << y.Tag() << std::endl;
std::cout << "after:  " << YAML::Dump(y) << std::endl;
```

prints 

```console
before: !x 42
tag:    !x
after:  !<!x> 42
```

## Expected:

```console
before: !x 42
tag:    x
after:  !x 42
```

I suppose two things are going wrong here:
1. The leading exclamation mark is added to the tag contents
2. The tag type changes from `_Tag::Type::PrimaryHandle` to `_Tag::Type::Verbatim`

So I have two questions: 
1. Is this a bug or am I doing it wrong? *I am not 100% sure I correctly understand the complicated yaml specs for tags...*
2. Is there any way to set the `_Tag::Type` for an existing node as a workaround?

**Comment by joergbrech** [comment]
I would be happy to contribute, if you would point me in the right direction. :grin:

**Comment by joergbrech** [comment]
@jbeder, just a short ping. Is this a bug? Can I contribute?

**Comment by TarangJ** [comment]
auto x = YAML::Node(42);

YAML::Emitter e;
e << YAML::Tag("x") << x; // Use YAML::Tag instead of YAML::LocalTag
std::string s = e.c_str();
auto y = YAML::Load(s);

std::cout << "before: " << s << std::endl;
std::cout << "tag:    " << y.Tag().substr(1) << std::endl; // Remove the first character "!" from the tag
std::cout << "after:  " << YAML::Dump(y) << std::endl;

**Comment by davidzchen** [comment]
I know this is an old bug, but has there been any updates on this?

**Comment by jbeder** [comment]
I don't think so. As usual, open to PRs.

**Comment by IMaloney** [comment]
Hey @jbeder @davidzchen, would it be possible to receive some feedback on my pr? Looking forward to fixing this bug :)
