### ISSUE TITLE
New formal release needed for MinGW64 users

### ISSUE THREAD

**Issue by HunterZ** [jbeder/yaml-cpp#1150]
Package managers for both MSYS and VCPKG currently ship yaml-cpp version 0.7.0 based packages for MinGW64 because it is the latest formal release. Unfortunately this results in build errors due to issue #1026, which was fixed long after 0.7.0 released. Any chance of a new formal release so that people don't have to forego the benefit of package managers in order to use yaml-cpp in their MinGW64 projects? Thanks!

**Comment by niva-xx** [comment]
Hi HunterZ,

It seems that i have same error on v0.7.0 using cmake 3.25 and mingw64 under MSYS2, 
any idea to solve it without taking previous version ?

```
[ 21%] Linking CXX executable yaml-cpp-tests.exe
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/yaml-cpp-tests.dir/objects.a(error_messages_test.cpp.obj):error_messages_test.cpp:(.text$_ZN4YAML6detail4node9push_backERS1_St10shared_ptrINS0_13memory_holderEE[_ZN4YAML6detail4node9push_backERS1_St10shared_ptrINS0_13memory_holderEE]+0x7a): undefined reference to `__imp__ZN4YAML6detail4node8m_amountE'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/yaml-cpp-tests.dir/build.make:308: yaml-cpp-tests.exe] Error 1
```

Thanks!

**Comment by HunterZ** [comment]
0.7.0 is broken. It's unusable. Here is the fix that was made sometime after it released: https://github.com/jbeder/yaml-cpp/issues/1026#issuecomment-1122305522

**Comment by WilliamTambellini** [comment]
+1 for a new release

**Comment by jbeder** [comment]
Just pushed [0.8.0](https://github.com/jbeder/yaml-cpp/releases/tag/0.8.0).
