### ISSUE TITLE
Iterating fails on Release build

### ISSUE THREAD

**Issue by Osteri** [jbeder/yaml-cpp#1153]
## Setup

File `register_info.yaml`:

```yaml
version: "1.0"
organisations:
  - name: "company x"
    registers:
      - name: "register x"
        address: "0x20"
        bitmask: "0x12"
      - name: "register y"
        address: "0x21"
        bitmask: "0xFF"
```

Code:

```cpp
  const auto file = "register_info.yaml";
  try {
    const auto yaml = YAML::LoadFile(file);
    const auto& registers = yaml["organisations"][0]["registers"];
    if (registers.IsSequence()) {
      std::cout << "Parsed registers: \n";
      for (const auto& r : registers) {
        const auto ri = r.as<RegisterInfo>();
        std::cout << " - \"" << std::get<const char*>(ri.name) << "\"\n";
      }
    }
  } catch (YAML::Exception& e) {
    std::cerr << e.what() << "\n";
    return EXIT_FAILURE;
  }
```

## Issue

when build with  `-DCMAKE_BUILD_TYPE=Debug` prints:

```
Parsed registers: 
 - "register x"
 - "register y"
```

when build with `-DCMAKE_BUILD_TYPE=Release` prints:
```
Parsed registers: 
 - ""
 - "register y"
```

**Comment by davemers0160** [comment]
@Osteri I'm having a similar problem when switching between debug and release versions on Windows.  Did you have any luck figuring this out?  My problem is that when I specify the filename in ::LoadFile I get "string too long" error.

What I've found so far, building a RelWithDebInfo version, is that the input string into ::LoadFile is getting mangled and is trash when it enters the function.  I've also tried a std::ifstream into ::Load, which is what ::LoadFile is doing, and that also fails to return a valid Node.

**Comment by Osteri** [comment]
@davemers0160 I haven't spend any time investigating this.

**Comment by Osteri** [comment]
Hi @H5117,

>Can't reproduce with Visual Studio 2022 v143

I'm using Linux:

```
g++ --version
g++ (GCC) 11.3.1 20220421 (Red Hat 11.3.1-3)
```

Code can be found from my gitlab repo. I didn't intentionally include it as the code is very complicated (and irrelevant IMO, but you never know).

You can reproduce this bug by:
```
git clone --recursive git@gitlab.com:osteri/register.git
cd register
cmake -S . -B build -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON
cd build
./example-linux.bin
```

Giving `-DCMAKE_BUILD_TYPE=Release` to `cmake` changes behaviour of the program in my system.

**Comment by Osteri** [comment]
YAML encoding/decoding of class `RegisterInfo` can be found here: https://gitlab.com/osteri/register/-/blob/main/src/linux/inc/linux_register.hpp

**Comment by H5117** [comment]
> ```
> git clone --recursive git@gitlab.com:osteri/register.git
> cd register
> cmake -S . -B build -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON
> cd build
> ./example-linux.bin
> ```
With this scenario I get
```
Parsed registers: 
 - ""
 - ""
```
both with and without `-DCMAKE_BUILD_TYPE=Release`. I think we need to write a minimal reproducer to understand what is going on.

Arch Linux
gcc 12.2.0-1

**Comment by Osteri** [comment]
Here is minimal reproducer with 3 files: `main.cpp`, `register_info.hpp` and `register_info.yaml`.

`main.cpp`:

```cpp
#include <yaml-cpp/yaml.h>
#include <fstream>
#include <iostream>
#include <vector>
#include <register_info.hpp>

int main () {
  const auto file = "register_info.yaml";
  try {
    const auto& yaml = YAML::LoadFile(file);
    const auto& registers = yaml["organisations"][0]["registers"];
    if (registers.IsSequence()) {
      std::cout << "Parsed registers: \n";
      for (const auto& r : registers) {
        const auto ri = r.as<RegisterInfo>();
        std::cout << " - \"" << std::get<const char*>(ri.name) << "\"\n";
      }
    }
  } catch (YAML::Exception& e) {
    std::cerr << e.what() << "\n";
    return EXIT_FAILURE;
  }
}

```

`register_info.hpp`:

```cpp
#pragma once

#include <yaml-cpp/yaml.h>
#include <variant>

using name_t = std::variant<const char*, std::uint64_t>;
using addr_t = std::uint8_t;
using bitmask_t = std::size_t;

class RegisterInfo {
 public:
  const name_t name{};
  const addr_t address{};
  const bitmask_t bitmask = std::numeric_limits<std::size_t>::max();
  const float factor = 1.0f;
};

/* Encode/decode RegisterInfo for yaml node */
namespace YAML {
template <>
struct convert<RegisterInfo> {
  static Node encode(const RegisterInfo& rhs) {
    Node node;
    node["name"] = std::get<const char*>(rhs.name);
    node["address"] = rhs.address;
    node["bitmask"] = rhs.bitmask;
    return node;
  }

  static bool decode(const Node& node, RegisterInfo& rhs) {
    std::string helper;
    try {
      const_cast<name_t&>(rhs.name) = node["name"].as<std::string>().c_str();
      helper = node["address"].as<std::string>();
      const_cast<addr_t&>(rhs.address) = std::stoul(helper, nullptr, 16);
      helper = node["bitmask"].as<std::string>();
      const_cast<bitmask_t&>(rhs.bitmask) = std::stoul(helper, nullptr, 16);
      return true;
    } catch (std::exception& e) {
      return false;
    }
  }
};
}  // namespace YAML
```
`register_info.yaml`:

```yaml
version: "1.0"
organisations:
  - name: "company x"
    registers:
      - name: "register x"
        address: "0x20"
        bitmask: "0x1"
      - name: "register y"
        address: "0x21"
        bitmask: "0xFF"

```

Clone `yaml-cpp` in same directory as the 3 files above and then link it:

```
g++ -Lyaml-cpp/build -Iyaml-cpp/include -I. -O2 -s -DNDEBUG main.cpp -lyaml-cpp -o main.bin
./main.bin
Parsed registers: 
 - ""
 - "register y"
```

Compiling without optimisations:

```
g++ -Lyaml-cpp/build -Iyaml-cpp/include -I.  main.cpp -lyaml-cpp -o main.bin
./main.bin
Parsed registers: 
 - "register x"
 - "register y"
```

**Comment by KitsuneRal** [comment]
yamlcpp has nothing to do with this. `std::string::c_str()` only holds a temporary buffer, it is not even guaranteed to live as long as its underlying string - which is also a temporary in your case. Also, as a rule - don't  use `const char *` if you are even slightly unsure about the lifecycle of the storage it points to, use `std::string` instead.

**Comment by Osteri** [comment]
You're right.

It was dangling pointer and run-time behaviour was random. So this can be closed. Solution is to change `const char*` -> `std::string`.
