### ISSUE TITLE
CMake build has targets that cannot be disabled

### ISSUE THREAD

**Issue by prybicki** [jbeder/yaml-cpp#1158]
I am using `yaml-cpp` in my project using `FetchContent`. I noticed that Makefile is polluted with targets such as:

```make
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
        $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
        $(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast
```

This causes CMake-based IDE such as CLion to show irrelevant targets:

![image](https://user-images.githubusercontent.com/25122246/204602321-90c96ef7-dc3d-4f18-b0d9-8f27c6dabeeb.png)

I have attempted to silence this down by:
```cmake
set(YAML_CPP_BUILD_TESTS OFF CACHE INTERNAL "Disable yaml-cpp artifacts")
set(YAML_CPP_BUILD_CONTRIB OFF CACHE INTERNAL "Disable yaml-cpp artifacts")
set(YAML_CPP_BUILD_TOOLS OFF CACHE INTERNAL "Disable yaml-cpp artifacts")
set(YAML_CPP_INSTALL OFF CACHE INTERNAL "Disable yaml-cpp artifacts")
set(YAML_CPP_FORMAT_SOURCE OFF CACHE INTERNAL "Disable yaml-cpp artifacts")
```
This works partially - e.g. `yaml-cpp-parse` disappears as expected, but targets Continuous*, Experimental*, Nightly* remain. Any ideas on how these targets can be disabled?

**Comment by sayo9394** [comment]
You can prevent those from being created by doing `set_property(GLOBAL PROPERTY CTEST_TARGETS_ADDED 1)` anywhere in your CMake code, before calling `enable_testing()`.

**Comment by prybicki** [comment]
Thanks, @sayo9394, it worked for me. Adding it just before `enable_testing()` did not work, but putting it in just after `project(...)` and before including dependencies (`find_package(...)` and `add_subdirectory(...)`) worked perfectly.
