### ISSUE TITLE
Accessing the name of a node?

### ISSUE THREAD

**Issue by GalladeGuy** [jbeder/yaml-cpp#1162]
Let's say you have something like this:
```
map:
    a: 1
    b: 2
    c: 3
```
If you only had YAML::Node pointing to, for example, that "b" node, is there any way to get "b" back as a string from it? I know you could get it if you had the root node, but it would simplify things if there was a name method or similar on the node itself.

**Comment by jbeder** [comment]
No, since (because of aliases) a node can have multiple "parents".
