### ISSUE TITLE
Parsing quoted numbers as strings, not int/float/double

### ISSUE THREAD

**Issue by NikOsint** [jbeder/yaml-cpp#1166]
The problem that I have faced using yaml-cpp library is that numbers (both integers and float/double) are always parsed as integers/float/double respectively regardless of the presence of quotes. In other libraries (for example, libyaml, which is used in PHP YAML module) data which is framed by quotes is always parsed as string (which, in my opinion, is a more correct way).

If there is a setting/method that allows me to make yaml-cpp behave like I have just described, please tell me, because I have not found any way to do so.

**Comment by jbeder** [comment]
yaml-cpp allows you to parse it any way you want, and lets you know if it thinks it should be a string by looking at the tag.

**Comment by NikOsint** [comment]
@jbeder thank you for such a quick response! Tags are something I haven't tried yet:)
