### ISSUE TITLE
About CTest in CMakeLists.txt

### ISSUE THREAD

**Issue by skjsnb** [jbeder/yaml-cpp#1180]
Hi 👋

I have read the `CMakeLists.txt` file in the root directory of the yam-cpp repository, and I noticed that `CTest` is globally referenced. Is there any reason for doing so? Would it be better to put it inside `if(YAML_CPP_BUILD_TESTS)`?

```
if(YAML_CPP_BUILD_TESTS)
    include(CTest)
    add_subdirectory(test)
endif()
```

Thank you for your attention.

**Comment by jbeder** [comment]
Sure! I basically accept any PRs about CMake.

**Comment by MatthijsBurgh** [comment]
Yes there is a reason, see #1170
