### ISSUE TITLE
How to check scalar type? (int vs float vs string)

### ISSUE THREAD

**Issue by mediumrarez** [jbeder/yaml-cpp#1186]
If I have a scalar `YAML::Node`, but don't know whether it's an int, float, or string, how do I check?

**Comment by jbeder** [comment]
If you're looking for automatic type detection, just try to parse it as an int or float and see if it works. If you've already specified it with a tag, you can call `GetTag()` and find out.

(Also, in the future, please ask questions like this on Stack Overfow.)
