### ISSUE TITLE
Add a Security-Policy

### ISSUE THREAD

**Issue by diogoteles08** [jbeder/yaml-cpp#1188]
Hi @jbeder! I'm Diogo and I'm back (see #1174) hoping to offer a bit more help with security enhancements.

This time I'm here to suggest that you expose a way that users can report eventual vulnerabilities in a safe and efficient way. This is usually described in a Security Policy, which is a GitHub standard document (SECURITY.md) added on the root of the repo and will be visible to the users in the "Security Tab".

![image](https://user-images.githubusercontent.com/22223372/225964433-be72a4a5-a57f-4b93-a138-6f2319e41c17.png)

It is a recommendation from [Github](https://docs.github.com/en/code-security/getting-started/securing-your-repository#setting-a-security-policy) itself, and from [Scorecard](https://github.com/ossf/scorecard/blob/main/docs/checks.md#security-policy) (being a security measure of medium priority).

Aiming to make this change easier, I'll take the liberty of submitting one suggestion of a Security Policy as a PR. Please feel free to edit it directly or ask me for editions until it is in compliance with how jbeder/yaml-cpp would best handle vulnerability reports.

**Comment by diogoteles08** [comment]
Hey @jbeder! This issue has been idle for quite some time. Do you plan on considering these changes? Otherwise I will wait up to 2 more months and close the issue.

Thanks!

**Comment by jbeder** [comment]
Merged, sorry for the delay!
