### ISSUE TITLE
"<<" operator

### ISSUE THREAD

**Issue by TheRoslyak** [jbeder/yaml-cpp#1197]
I started working with the yaml-cpp library. The GPT chat suggested to me that the "<<" operator is part of the YAML syntax and is used to merge data from one node into another. However, the yaml-cpp library we are using does not support this operator by default. Is this true? Does it make sense to upgrade the library, or was the chat incorrect?

**Comment by jbeder** [comment]
https://arstechnica.com/tech-policy/2023/05/lawyer-cited-6-fake-cases-made-up-by-chatgpt-judge-calls-it-unprecedented/
