### ISSUE TITLE
New release? 🤔

### ISSUE THREAD

**Issue by kloczek** [jbeder/yaml-cpp#1204]
https://github.com/jbeder/yaml-cpp/compare/yaml-cpp-0.7.0...master shows almost 50 commits since last release which was in 2021.

Do you have any plans to flush those commits and release new version? 🤔 

BTW it would be good to change tagging convention from `yaml-cpp-<version>` to just `<version>` because autogenerated from git tag tar ball automatically forms archive with base directory `<repo-name>-<git.tag>`.

**Comment by jbeder** [comment]
Just pushed [0.8.0](https://github.com/jbeder/yaml-cpp/releases/tag/0.8.0).

**Comment by kloczek** [comment]
Thank you very much 👍 😄
