### ISSUE TITLE
Compiling Warning messages from YAML-CPP

### ISSUE THREAD

**Issue by ju-liu** [jbeder/yaml-cpp#1208]
Hi:

When compiling the yaml-cpp code on mac, several warning messages are noted by the compiler.
1. 
In file included from /Users/juliu/lib/yaml-shared/include/yaml-cpp/yaml.h:12:
/Users/juliu/lib/yaml-shared/include/yaml-cpp/emitterstyle.h:12:25: warning: declaration shadows a variable in namespace 'YAML' [-Wshadow]
  enum value { Default, Block, Flow };
                        ^
/Users/juliu/lib/yaml-shared/include/yaml-cpp/emittermanip.h:59:3: note: previous declaration is here
  Block,

2.
In file included from /Users/juliu/lib/yaml-shared/include/yaml-cpp/yaml.h:12:
/Users/juliu/lib/yaml-shared/include/yaml-cpp/emitterstyle.h:12:32: warning: declaration shadows a variable in namespace 'YAML' [-Wshadow]
  enum value { Default, Block, Flow };
                               ^
/Users/juliu/lib/yaml-shared/include/yaml-cpp/emittermanip.h:58:3: note: previous declaration is here
  Flow,

3.
In file included from /Users/juliu/lib/yaml-shared/include/yaml-cpp/yaml.h:16:
In file included from /Users/juliu/lib/yaml-shared/include/yaml-cpp/node/node.h:18:
/Users/juliu/lib/yaml-shared/include/yaml-cpp/node/type.h:12:27: warning: declaration shadows a variable in namespace 'YAML' [-Wshadow]
  enum value { Undefined, Null, Scalar, Sequence, Map };
                          ^
/Users/juliu/lib/yaml-shared/include/yaml-cpp/null.h:23:27: note: previous declaration is here
extern YAML_CPP_API _Null Null;

**Comment by jbeder** [comment]
Thanks! I'm not too worried about warnings.
