### ISSUE TITLE
Bazel Central Registry release

### ISSUE THREAD

**Issue by stonier** [jbeder/yaml-cpp#1229]
Related to #1224.

@jbeder would you be able to add the `0.8.0` source tarball as an asset to the 0.8.0 release? 

**Example**: https://github.com/stonier/yaml-cpp/releases/tag/0.8.0-1

**Rationale**: Pointing at the source tarball url's attached to a release is apparently unstable. 

```
You should use a release archive URL in the format of `https://github.com/<ORGANIZATION>/<REPO>/releases/download/<version>/<name>.tar.gz` to ensure the archive checksum stability.
See https://blog.bazel.build/2023/02/15/github-archive-checksum.html for more context.
```

If that's there, I can apply the changes I made in #1224 as bazel module patches. Future releases won't need those patches.

Alternatively I can simply release from https://github.com/stonier/yaml-cpp/releases/tag/0.8.0-1 until the next `yaml-cpp` release arrives.

**Comment by zaucy** [comment]
I created a PR to automatically create the archive on release for future versions https://github.com/jbeder/yaml-cpp/pull/1230. A manual archive for `0.8.0` would still be required :)

**Comment by stonier** [comment]
> I created a PR to automatically create the archive on release for future versions https://github.com/jbeder/yaml-cpp/pull/1230. A manual archive for 0.8.0 would still be required :)

That's nice ... I'd not gotten around to working out how to do that, now I don't have to - thanks!

**Comment by stonier** [comment]
> @jbeder would you be able to add the 0.8.0 source tarball as an asset to the 0.8.0 release?

@jbeder if you can get around to this that'd be great, otherwise we'll switch across to it in future releases.
