### ISSUE TITLE
how to build yaml-cpp for aarch64?

### ISSUE THREAD

**Issue by njuhang** [jbeder/yaml-cpp#1236]
I use cmake .. and make, then libyaml-cpp.a is incompatibel with aarch64linux

**Comment by jbeder** [comment]
Can you give more details? Is there a reason it's incompatible?

**Comment by njuhang** [comment]
Because if I use cmake ..&& make, it will be built for x64 platform. Now I need to cross compile it for android aarch64 platform.

**Comment by jbeder** [comment]
What happens if you use cmake's cross compilation tools?

**Comment by njuhang** [comment]
But I don't know how to do cross compilation now.

**Comment by jbeder** [comment]
Have you tried looking it up?

**Comment by njuhang** [comment]
Sorry, could you please let me know what options I can set for aarch64 cross compilation?

**Comment by jbeder** [comment]
Your question isn't yaml-cpp specific. Just ask in general on the internet and I'm sure you'll get an answer.
