### ISSUE TITLE
Unresolve external symbol "__declspec(dllimpor) xxx"

### ISSUE THREAD

**Issue by CowNowK** [jbeder/yaml-cpp#1260]
I have linked the library, what should i do?

**Comment by CowNowK** [comment]
I just solved it myself. I just need to delete `__declspec(dllimport)` in `dll.h`.

**Comment by bluenlive** [comment]
> I just solved it myself. I just need to delete `__declspec(dllimport)` in `dll.h`.

Defining `YAML_CPP_STATIC_DEFINE` could be neater solution.

```
#define YAML_CPP_STATIC_DEFINE
#include "yaml.h"
```
