### ISSUE TITLE
Release file name 0.8.0 breaks naming convention

### ISSUE THREAD

**Issue by HFTrader** [jbeder/yaml-cpp#1262]
I have a script that sources `yaml-cpp-${VERSION}.tar.gz` but now version 0.8.0 is named only `0.8.0.tar.gz`. Is that intended? 
Can this be rolled back by any chance?

**Comment by jbeder** [comment]
I forget why I did that, but I think someone suggested it was redundant to have the yaml-cpp. Anyways you probably can just update your script?

**Comment by HFTrader** [comment]
Sure I can do that. However yours is the only sore thumb in a list of +50 other github repos that does not follow the convention.

**Comment by jbeder** [comment]
Oh, interesting. I there some github documentation to suggest what to do here? I can't seem to find the issue where someone complained in the other direction...

**Comment by jbeder** [comment]
Ah, I found it: https://github.com/jbeder/yaml-cpp/issues/1204#issue-1817047122

> BTW it would be good to change tagging convention from yaml-cpp-<version> to just <version> because autogenerated from git tag tar ball automatically forms archive with base directory <repo-name>-<git.tag>.

**Comment by jbeder** [comment]
Interesting. It names the URL `0.8.0.tar.gz` but when you click to download it, it saves it as `yaml-cpp-0.8.0.tar.gz`.

How are you downloading it?

**Comment by HFTrader** [comment]
The usual way to automate it is to download with tools like `curl` or `wget` as in 
```bash
$ wget http://ftp.gnu.org/gnu/binutils/binutils-2.33.1.tar.gz

$ ls -l
-rw-rw-r-- 1 user user 43367689 Oct 12  2019 binutils-2.33.1.tar.gz

$ tar taf binutils-2.33.1.tar.gz | head
binutils-2.33.1/setup.com
binutils-2.33.1/zlib/inffast.h
binutils-2.33.1/zlib/ChangeLog.jit
binutils-2.33.1/zlib/trees.h
binutils-2.33.1/zlib/doc/rfc1951.txt
binutils-2.33.1/zlib/doc/algorithm.txt
binutils-2.33.1/zlib/doc/rfc1950.txt
```
All the GNU ecosystem and most commercial/OSS Github packages do that name+version convention.
