### ISSUE TITLE
Newest commit breaks build

### ISSUE THREAD

**Issue by lukas-wresch** [jbeder/yaml-cpp#1306]
Hi,

commit 1f5e971f77cdb3a06185b7e134549cc52906da68 breaks the build for me.

yaml-cpp/include/yaml-cpp/emitterstyle.h:13:2: error: extra ‘;’ [-Wpedantic]

```
namespace EmitterStyle {
enum value { Default, Block, Flow };
};
```

I believe the last semicolon is the problem.

**Comment by jbeder** [comment]
Sorry, reverted.

**Comment by lukas-wresch** [comment]
Thank you!! :-)
