### ISSUE TITLE
uint8_t gets parsed a char then cast to a uint8_t

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jbeder/yaml-cpp#201]
```
rhs.initialTestingInput=node["initialTestingInput"].as<uint8_t>();

if my yaml file has the key initialTestingInput assigned to say 1, then 
initialTestingInput in my structure will have the value 49 ('0' + 1)

Not clear this is the desired behavior. But also not clear how to handle this 
properly since uint8_t is typedefed as a char...

For the moment I am avoiding uint8_t ...
```

Original issue reported on code.google.com by `zouhair....@gmail.com` on 19 Apr 2013 at 6:55

**Comment by alepinio** [comment]
Hi, any progress here?

Today I lost many hours until I realize this was the problem...error log it's just:

yaml-cpp: error at line 0, column 0: bad conversion

THX, Alejandro

**Comment by jbeder** [comment]
This is a super old bug. Please open a new bug with a reproducible example that you're currently running into.
