### ISSUE TITLE
Google Code Shutting Down

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jbeder/yaml-cpp#287]
```
Is there a plan for where this project will move?
```

Original issue reported on code.google.com by `UGWil...@gmail.com` on 23 Mar 2015 at 9:23

**Comment by WrinklyNinja** [comment]
The exporter seems to have done horrible things to your repository's history, there's orphan branches all over the place, which makes things like diffing changes very messy.

I tried the exporter too, and got the same result. I did convert the repository [before](https://github.com/WrinklyNinja/yaml-cpp) without any obvious problems, but I can't remember how I did this...

**Comment by jbeder** [comment]
Getting the current status on the record: WrinklyNinja used fast-export to get a conversion of the repo that didn't mess up history. I'm waiting on confirmation that I followed the instructions correctly, and that everything is OK here.

**Comment by jbeder** [comment]
Everything seems good!
