### ISSUE TITLE
does not parse null value

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jbeder/yaml-cpp#289]
```
Emitter correctly emits "~" for emtpy/null node but parser loads "~" as a 
string.
Tested versions 0.5.1, trunk.
```

Original issue reported on code.google.com by `sir...@dasir.cz` on 27 Mar 2015 at 9:50

**Comment by jbeder** [comment]
Fixed by 52bcefa1f18947bac98288b00188551046edb948, test added in bfb5703ce92b18e1f2d974a7c567a003184b64b0.
