### ISSUE TITLE
Emitter styling settings overridden by node settings.

### ISSUE THREAD

**Issue by Ortham** [jbeder/yaml-cpp#298]
The following test passes in 9880b608b931dd83363016914988367ca1212d49 but fails in the next commit, 0c280724e96787d08147cdca0bfe2c1123eb258d.

```
TEST_F(EmitterTest, GlobalSettingsNodeStyles) {
    Node node = Load("foo:\n"
                "  - 1\n"
                "  - 2\n"
                "  - 3\n"
                "bar: baz\n");

    out.SetSeqFormat(YAML::Flow);
    out.SetMapFormat(YAML::Flow);

    out << node;

    ExpectEmit("{foo: [1, 2, 3], bar: baz}");
}
```

The failing actual value is `foo:\n  - 1\n  - 2\n  - 3\nbar: baz`. I'd expect setting formatting on the emitter to override any preserved styling from when the node was parsed.

Commenting out the two `node.set_style(style);` lines added to `src/nodebuilder.cpp` in the latter commit prevents the issue occurring, but it's not really a fix...

**Comment by WrinklyNinja** [comment]
Closing this as it got fixed at some point in `master`.

**Comment by shnkr** [comment]
@Ortham: Issue still exists and the workaround you mentioned still works.

**Comment by Ortham** [comment]
I'll reopen this then, though I no longer use this functionality in yaml-cpp myself.
