### ISSUE TITLE
segfault on access

### ISSUE THREAD

**Issue by tmladek** [jbeder/yaml-cpp#299]
Relevant portion of the code:

    ...
	YAML::Node fluff = YAML::LoadFile("fluff.yaml");
	for (auto name : fluff["names"]["places"]){          // <- segfault here
		std::string strname = name.as<std::string>();
		names.push_back(strname);
	}
    ...

Backtrace:

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff6db9b64 in std::string::assign(std::string const&) () from /usr/lib/libstdc++.so.6
    (gdb) bt
    #0  0x00007ffff6db9b64 in std::string::assign(std::string const&) () from /usr/lib/libstdc++.so.6
    #1  0x0000000000518805 in operator= (__str=..., this=0x7fffffffd8a0) at /usr/include/c++/4.9.2/bits/basic_string.h:555
    #2  decode (rhs="", node=...) at /usr/local/include/yaml-cpp/node/convert.h:45
    #3  equals<std::basic_string<char> > (pMemory=..., rhs="names", node=...) at /usr/local/include/yaml-cpp/node/detail/impl.h:147
    #4  YAML::detail::node_data::get<std::string> (this=0xab6c70, key="names", pMemory=...) at /usr/local/include/yaml-cpp/node/detail/impl.h:96
    #5  0x00000000005191ed in get<std::basic_string<char> > (pMemory=..., key="names", this=<optimized out>)
        at /usr/local/include/yaml-cpp/node/detail/node_ref.h:52
    #6  get<std::basic_string<char> > (pMemory=..., key="names", this=0xab6840) at /usr/local/include/yaml-cpp/node/detail/node.h:103
    #7  YAML::Node::operator[]<char [6]> (this=this@entry=0x7fffffffdb30, key=...) at /usr/local/include/yaml-cpp/node/impl.h:392
    #8  0x00000000005125ca in Game::Game (this=0x7fffffffde50, gui=<optimized out>) at /home/foo/bar/Game.cpp:11
    #9  0x00000000004752ca in main (argc=1, args=0x7fffffffe3f8) at /home/foo/bar/main.cpp:84

And the YAML file:

    ---
    names:
      places:
        - Berlin
        - London
        - Paris
    ...

I'd be glad to post more details, but the problem absolutely escapes me. I'm using `yaml-cpp` 0.5.2-2 from Archlinux community repos and it used to work for some time; then, without any changes to the code, it started segfaulting when built on one machine, then on the other as well. It's very much possible that this is just an issue on my side, but I've ran out of troubleshooting options, so any help is appreciated!

**Comment by tmladek** [comment]
Also, I did find some issues which looked relevant, but none of them was helpful:

https://code.google.com/p/yaml-cpp/issues/detail?id=140  
https://code.google.com/p/yaml-cpp/issues/detail?id=270

**Comment by jbeder** [comment]
I see you posted on SO that when you remove the package, it fails to find it for compilation; can you confirm that you also don't have an extra copy for linking? I'm worried that you're linking to the wrong library.

**Comment by tmladek** [comment]
How would I go about that?

**Comment by jbeder** [comment]
Check

/usr/lib/libyaml-cpp*
/usr/local/libyaml-cpp*

maybe also

/opt/lib/libyaml-cpp*
/opt/local/lib/libyaml-cpp*

and any other places your system might happen to store libraries.

**Comment by tmladek** [comment]
And you were correct! I'm sorry for bothering you with such a simple issue and thank you!

**Comment by jbeder** [comment]
No problem :)

**Comment by boblehest** [comment]
Thanks for mentioning it here though, probably saved me a lot of time. :)
Same issue, same OS.
