### ISSUE TITLE
Exception thrown in as method when default supplied

### ISSUE THREAD

**Issue by JonHodgson** [jbeder/yaml-cpp#305]
Perhaps I'm missing something here, but I've been successfully using an earlier version of yaml-cpp with my code containing lines such as this

    std::string group = attributes["group"].as<std::string>("");

the node "group" may not exist, but that's why there's a default.

However I just updated the yaml-cpp source, and now there is an additional check in "as"

    if (!m_isValid)
      throw InvalidNode();

So, if the node doesn't exist, rather than just returning the default value, an exception is thrown.

This doesn't make sense to me. I can understand throwing an exception when no default value is supplied, but not when it is.

**Comment by jbeder** [comment]
Thanks, this is definitely a mistake.

**Comment by jbeder** [comment]
This was fixed by #316, b426fafff6238dda8d86fa668f585cba732dd272.
