### ISSUE TITLE
"unresolved external symbol" error when using yaml-cpp as a static library in Visual Studio 2013

### ISSUE THREAD

**Issue by tasmanianfox** [jbeder/yaml-cpp#332]
I compiled yaml-cpp as a static library using Visual Studio Community 2013 and added the library to my project. This code works fine:
```
#include <yaml-cpp/yaml.h>
...

YAML::Node node = YAML::Load("{name: Brewers, city: Milwaukee}");
std::cout << node.size();
```
However, this code causes an error:
```
#include <yaml-cpp/yaml.h>
...

YAML::Node node = YAML::Load("{name: Brewers, city: Milwaukee}");
std::cout << node["name"];
```
Output is below:
```
1>------ Build started: Project: myapp, Configuration: Debug Win32 ------
1>  Application.cpp
1>Application.obj : error LNK2001: unresolved external symbol "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > YAML::detail::node_data::empty_scalar" (?empty_scalar@node_data@detail@YAML@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@A)
1>D:\code\cpp\myapp\Debug\myapp.exe : fatal error LNK1120: 1 unresolved externals
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

GCC compiles both codes successfully.

**Comment by mmatrosov** [comment]
Same for me! Is there any workaround?

**Comment by mmatrosov** [comment]
Oh, seems like it is not a bug, you just need to define `YAML_CPP_DLL` in your project.

**Comment by tasmanianfox** [comment]
Thanks, @mmatrosov ! ```#define YAML_CPP_DLL``` solved the problem.

**Comment by CrackHD** [comment]
Strange, i do not have this problem. And this macro serves another purpose, as it seems.

**Comment by mmatrosov** [comment]
@CrackHD This marco serves exactly this purpose. However, you wouldn't face it if you link yaml-cpp statically. This is only needed if you are linking with a dynamic library.
