### ISSUE TITLE
cmake error - Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by shahn87** [jbeder/yaml-cpp#334]
I'm building it for using in Xcode.
So I just followed the steps written in Install.txt.
But, everytime I start "cmake -G Xcode ..", I got same error. 
`-- Found Threads: TRUE`
`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.`
`Please set them or make sure they are set and tested correctly in the CMake files:`
`Boost_INCLUDE_DIR (ADVANCED)`
`   used as include directory in directory {YAML_CPP_PATH}`
`   used as include directory in directory {YAML_CPP_PATH} `
`   used as include directory in directory {YAML_CPP_PATH}/test`
`   used as include directory in directory {YAML_CPP_PATH}/test/gmock-1.7.0`
`   used as include directory in directory {YAML_CPP_PATH}/test/gmock-1.7.0`
`   used as include directory in directory {YAML_CPP_PATH}/test/gmock-1.7.0/gtest`
`   used as include directory in directory {YAML_CPP_PATH}/test/gmock-1.7.0/gtest`
`   used as include directory in directory {YAML_CPP_PATH}/util`
`   used as include directory in directory {YAML_CPP_PATH}/util`
`   used as include directory in directory {YAML_CPP_PATH}/util`

How can I fix it?

**Comment by jbeder** [comment]
It looks like you have to install Boost first.
