### ISSUE TITLE
Removing boost dependency

### ISSUE THREAD

**Issue by CrackHD** [jbeder/yaml-cpp#340]
Asking again, why not remove boost dependency from that project? 

I really don't like to carry boost with my application, i don't need it, like most of users of yaml-cpp. 
I think it's an issue of this project, the most important one for now left.

Recent commit "removing boost from memory.h" did not solve dependency. 
Anyone has any time for doing this?

**Comment by winterheart** [comment]
See #309

**Comment by blair1618** [comment]
Now submitted as https://github.com/jbeder/yaml-cpp/pull/342

**Comment by jbeder** [comment]
Fixed 24fa1b33805c9a91df0f32c46c28e314dd7ad96f.
