### ISSUE TITLE
Writing a value with a single double quote character creates invalid YAML

### ISSUE THREAD

**Issue by peterhuene** [jbeder/yaml-cpp#346]
The following code:

```c++
emitter << YAML::BeginMap;
emitter << YAML::Key << "foo" << YAML::Value << '"';
emitter << YAML::EndMap;
```

Results in this invalid YAML:

```yaml
foo: """
```

Expected the character to be treated the same as a string of size 1 containing just a double quote character.  I suspect there are characters other than double quote that would also cause invalid YAML generation.

Workaround:

```c++
... << YAML::Value << std::string(1, '"');
```

This results in the correct escaped character:

```yaml
foo: "\""
```

**Comment by jbeder** [comment]
Fixed, r36fd93a8d5fec69fe75ae8215541359276f0606c.

**Comment by jbeder** [comment]
36fd93a8d5fec69fe75ae8215541359276f0606c

**Comment by peterhuene** [comment]
Thank you!
