### ISSUE TITLE
typo in the wiki page "How to Emit YAML"

### ISSUE THREAD

**Issue by mbionchi** [jbeder/yaml-cpp#352]
In the Using Manipulators section, the piece of code that deals with sequences is:
```
out << YAML::BeginSeq << 2 << 3 << 5 << 7 << 11 < YAML::EndSeq;
```
which for those of us who blindly copy-and-paste stuff will cause an error, since operator < is not defined for these types and it more than likely should say <<, like this:
```
out << YAML::BeginSeq << 2 << 3 << 5 << 7 << 11 << YAML::EndSeq;
```

**Comment by jbeder** [comment]
Thanks, fixed.
