### ISSUE TITLE
Ambiguous networking strings are output without quotes

### ISSUE THREAD

**Issue by MikaelSmith** [jbeder/yaml-cpp#359]
Some common networking formats - mac addresses and IPv6 - can result in valid sexagesimal strings. YAML (at least Ruby YAML) will parse them as numbers (see http://blog.teamlazerbeez.com/2009/04/15/yaml-gotchas/ for one source).

Some examples
```
irb(main):001:0> require 'yaml'
=> true
irb(main):002:0> YAML.load 'mac: 00:50:56:55:42:45'
=> {"mac"=>9877556}
irb(main):003:0> YAML.load 'ipv6: 10:10:10:10:10:10:10:10'
=> {"ipv6"=>7907833210}
irb(main):004:0> YAML.load '01:10: 10:12'
=> {4200=>36720}
```

I assume times are desirable to leave unparsed. It seems like there should be some explicit way of requesting sexagesimal-compatible output, and the rest of the time potentially ambiguous strings should be quoted.

**Comment by jbeder** [comment]
To make sure I understand what you're saying:

If, in yaml-cpp, you write something like

```
YAML::Node node;
node["mac"] = "00:50:56:55:42:45";
std::cout << YAML::Dump(node);

```

It'll produce `mac: 00:50:56:55:42:45`. And then if you try to read that YAML in Ruby YAML, it'll parse the value as an integer. Is this correct?

If so, have you tried bringing this up with the Ruby YAML project? YAML 1.2 lists several [schema](http://www.yaml.org/spec/1.2/spec.html#Schema) that you can use to serialize/deserialize raw strings, but I don't believe this is one of them.

**Comment by MikaelSmith** [comment]
Ah, I saw it in the [working draft](http://yaml.org/spec/spec.html). It's also in yaml 1.1. So it may be they support an older specification of the language.

I'll accept this is a mismatch I need to handle separately.
