### ISSUE TITLE
Nodes loaded from file read-only?

### ISSUE THREAD

**Issue by EMC3** [jbeder/yaml-cpp#363]
Hello,

I wrote this simple code:

YAML::Node n = YAML::LoadFile(file); // as described in the tutorial

I have no problems accessiong the contents of n, and the file exists. But as soon as i write

n["whatever"] = somevalue;

i get an YAML::BadSubscript exception (what():  operator[] call on a scalar). Is this a bug or are loaded nodes read-only? If i create the node by writing

YAML::Node n;

i can write into without any problem.

Thanks

**Comment by jbeder** [comment]
The error message indicates that `n` is a scalar, not a map. You cannot set a key/value pair in a scalar (what would it do?).

Also, note that on the README, it says:

> If you have questions about how to use yaml-cpp, please post it on http://stackoverflow.com and tag it yaml-cpp
