### ISSUE TITLE
yaml-0.2.7 GetNextDocument() hit assertion fail in Scanner::peek

### ISSUE THREAD

**Issue by yijiem** [jbeder/yaml-cpp#364]
Hi yaml-cpp team,

I am using yaml-0.2.7 and I hit an assertion in Scanner::peek function line 41 assert(!m_tokens.empty()); by providing an incomplete json text to parser and then doing parser.GetNextDocument, here is the test case:
```
int main(int argc, char **argv) {
    // char buf[] = "{\"access\":\"abc\"}"; // this is the correct json

    char buf[] = "{\"access\""; // hit assertion
    // char buf[] = "{\"access\":"; // hit assertion
    // char buf[] = "{\"access\":\""; // hit assertion
    // char buf[] = "{\"access\":\"abc"; // won't hit assertion
    // char buf[] = "{\"access\":\"abc\""; // hit assertion
    try {
        std::istringstream iss(buf);
        YAML::Parser parser(iss);
        YAML::Node doc;
        parser.GetNextDocument(doc);
    } catch (const YAML::Exception &e) {
        std::cout << "YAML::Exception receive" << std::endl;
    }
    return 0;
}
```
**Seems like if the string is truncated at double quote or control character, it will hit that assertion.**

For reason why I am using an incomplete json text, here is the stackoverflow link where I post my original question:
http://stackoverflow.com/questions/35449592/yaml-0-2-7-getnextdocument-hit-assertion-fail-in-scannerpeek/35458364#35458364

Will it help if I upgrade to the latest 0.5.3 version? I looked at the source code and saw the same assertion in Scanner::peek function is still there.

Much appreciate for the help!

**Comment by jbeder** [comment]
It appears this is fixed (not sure when). I added tests in 178c8d1f276afeec006e2c4e1dfa979c1f9d2a3c, but it should work in 0.5.3.
