### ISSUE TITLE
Documentation for parsing a stream

### ISSUE THREAD

**Issue by leehambley** [jbeder/yaml-cpp#372]
Please forgive me for opening an issue which is more like a question, I couldn't even find enough to go on to write a 1/2 decent SO question and pick you up over there.

I'm wondering if there's a way to parse a file with `yaml-cpp` but to retain the information about where a certain node came from, I tend to think it'd be possible somehow, even just to get the byte offset of the parser, and I could figure out the line number myself.

Is that possible? I see the guide just deals with parsing data, and getting representative C++ types from YAML, but for my use-case the origin of the key/fragment/chunk (*ahem*`Node`*ahem*) is important.

Thanks, and sorry for the (probably inappropriate) issue spam.

**Comment by Tricertops** [comment]
Documentation is really lacking here. Have a look at [`YAML::Node::Mark()`](https://github.com/jbeder/yaml-cpp/blob/master/include/yaml-cpp/node/node.h#L52) which should hold information about position, line and column in the source string.

**Comment by leehambley** [comment]
Thanks @Tricertops that was some epic response time, I'll see if I can work with that at all, and if so maybe I can PR for a doc improvement. I was down the (albeit shallow) rabbit hole in https://github.com/jbeder/yaml-cpp.new-api/blob/master/src/parse.cpp

**Comment by jbeder** [comment]
Happy to accept documentation PRs - sorry about the poor state of the docs; closing this issue since it seems resolved.
