### ISSUE TITLE
Unable to build on Cygwin

### ISSUE THREAD

**Issue by SirLoxley** [jbeder/yaml-cpp#373]
Hello,
I ran into a problem building on Cygwin with g++ due to GTest requiring non-ansi extensions
(compare http://stackoverflow.com/questions/18784112/googletest-1-6-with-cygwin-1-7-compile-error-fileno-was-not-declared-in-thisz)

I am going to submit a PR, the fix is relatively easy - g++ needs a different compiler switch (in test/CMakeList.txt).

**Comment by SirLoxley** [comment]
https://github.com/jbeder/yaml-cpp/pull/374

**Comment by SirLoxley** [comment]
Sorry, reopening, not familiar with github

**Comment by jbeder** [comment]
Thanks! Fixed by #374
