### ISSUE TITLE
Are downloads provided other than github? 

### ISSUE THREAD

**Issue by stahnma** [jbeder/yaml-cpp#385]
When I download yaml-cpp from github, it's named release-0.5.3.zip (for the last tag) which is super unhelpful when also downloading other components to build up all at once. Is there any chance of providing downloads with filenames that most tools expect like yaml-cpp-0.5.3.tar.gz and having it unpack into yaml-cpp-0.5.3? Right now, this an oddity and we have to repack it by hand. I realize this is perhaps a shortcoming of our workflow, but having archives with non-identifiable information in the name and then extracting to a somewhat surprising directory name also doesn't seem wonderful.

**Comment by jbeder** [comment]
Good point, I never thought of this. I changed the latest release to yaml-cpp-0.5.3 and will continue to name tags like that in the future.
