### ISSUE TITLE
considering using pragma for VC++

### ISSUE THREAD

**Issue by xuboying** [jbeder/yaml-cpp#392]
considering adding following pragma for linking which supported by VC++

I have to put following in my source code to support dynamic lib choice based on DEBUG/RELEASE version, these code can actually be written in framework(header file)
Thanks.

```c++
#if defined(_MSC_VER)
#if defined(_DEBUG)
#pragma comment(lib, "libyaml-cppmdd.lib")
#else
#pragma comment(lib, "libyaml-cppmd.lib")
#endif
#endif

```

**Comment by jbeder** [comment]
Why would this go in the framework rather than in a client application?

**Comment by xuboying** [comment]
if you are using visual studio, you shall let VS know which lib file to link with(presume static link). I learnt this from some big project(wxWidgets), and use it in my frameworks. https://github.com/xuboying/PCRE2Plus/blob/master/src/PCRE2Plus.h (line 44-61), so the client app don't have to repeat this. Sorry I'm not sure how about DLL link pragma.

**Comment by jbeder** [comment]
But client applications typically have to say what library they link to. Why should VS be different?

**Comment by xuboying** [comment]
Sorry, I built the 0.5.3 release quite some time ago and now I forgot how I actually built it, 
but eventually, I only use following two files, perhaps the same as other VC++ users
C:\usr\lib\yaml-cpp-release-0.5.3\build
> dir /b /s | perl -ne "print if /(Release|Debug).*lib$/"
C:\usr\lib\yaml-cpp-release-0.5.3\build\Debug\libyaml-cppmdd.lib
C:\usr\lib\yaml-cpp-release-0.5.3\build\Release\libyaml-cppmd.lib
So the framework can predict which lib to be used and pre-define them for users

Some reference
https://stackoverflow.com/questions/36490750/avoid-specifying-link-input-parameter-in-vc-for-static-link

https://msdn.microsoft.com/en-us/library/7f0aews7.aspx

**Comment by jbeder** [comment]
OK, thanks for the information. I don't think we're going to add this in code.

**Comment by xuboying** [comment]
No worries
