### ISSUE TITLE
Access Denied to ALL_BUILD

### ISSUE THREAD

**Issue by rielt12** [jbeder/yaml-cpp#403]
Hello,

I am not able to run any of the programs in the library because my access is denied.
I am running visual studio as an administrator.
It says that ALL_BUILD is denied.
![image](https://cloud.githubusercontent.com/assets/13559351/17564062/1e29c6be-5f00-11e6-9672-06ba2d391f16.png)

**Comment by jbeder** [comment]
This isn't related to yaml-cpp. Check your system's permissions.
