### ISSUE TITLE
Is event-driven parsing supported? Can I use YAML::Parser from yaml-cpp/parser.h?

### ISSUE THREAD

**Issue by adambadura** [jbeder/yaml-cpp#409]
[Tutorial](https://github.com/jbeder/yaml-cpp/wiki/Tutorial) shows only the `YAML::Load` function.

As simple and nice is that, it has however a disadvantage. It reads entire document into memory. While that is not always needed.

In my particular case I want to read YAML into [Boost.PropertyTree](http://www.boost.org/libs/property_tree/). So I don't need entire `YAML::Node` since I'm not going to use it anyway (for anything else than conversion to `boost::property_tree::ptree`). It seems that event-driven parsing would be more than enough.

Now there is this file `yaml-cpp/parser.h` with `YAML::Parser` class that looks just like what I would need. But since the [Tutorial](https://github.com/jbeder/yaml-cpp/wiki/Tutorial) doesn't seem to mention it I'm somewhat afraid to use it as perhaps something meant as internal detail and a subject for future changes.

So is it safe to use it? If so then are there any guidelines for its use?

I expect to have small YAML files so this isn't really a big issue for me. I can live with that `YAML::Load` just as well. But still it seems this could be just "cleaner".

Also, by the way, since yaml-cpp uses Boost anyway, it could be reasonable to deliver [Boost.PropertyTree](http://www.boost.org/libs/property_tree/) extension so that yaml-cpp users will have proper parser readily available. And even if [yaml-cpp 0.5.3](https://github.com/jbeder/yaml-cpp/releases/tag/release-0.5.3) indeed would be the last release to use Boost such an extension could still be easily delivered I think.

**Comment by jbeder** [comment]
You definitely can use YAML::Parser; it's not well documented, but should solve your use case.

yaml-cpp no longer depends on boost, so I don't think we'll add a new one.

**Comment by adambadura** [comment]
Then at least considering adding a note in documentation about that `YAML::Parser`. :)
