### ISSUE TITLE
How to emit a comma list?

### ISSUE THREAD

**Issue by rielt12** [jbeder/yaml-cpp#417]
Hello 

I have a 9 3x3 matrix of all zeroes. I am trying to output it in row major form so that it will look like.
covariance: 0,0,0,0,0,0,0,0,0,

I have tried  
out1 << YAML::Key << "covariance";
out1 << YAML::Literal<< covariance[0][0]<< "," << covariance[0][1]... etc.
But i get :

covariance: 0
    ",": 0
what am I doing wrong?

thanks

**Comment by jbeder** [comment]
If you want 

```
covariance: [0,0,0,0,0,0,0,0,0]
```

Then you can use

```
out << YAML::Key << "covariance";
out << YAML::Value << YAML::BeginSeq;
for (int i=0;i<N;i++) {
  out << covariance[0][i];
}
out << YAML::EndSeq;
```

Also, please ask questions like this on stackoverflow.com and tag them `yaml-cpp`.

**Comment by rielt12** [comment]
would it be possible to get it without the brackets? Or does that not make a difference?

**Comment by jbeder** [comment]
If you want it without the brackets, just make a string directly and output that.
