### ISSUE TITLE
nan, inf and friends emitted w/o leading period

### ISSUE THREAD

**Issue by till-s** [jbeder/yaml-cpp#420]
Thanks for yaml-cpp! I'm using 0.5.3 and noticed that yaml-cpp encodes nan/inf etc. without a leading period.
[emitting-nan-tst.cc.txt](https://github.com/jbeder/yaml-cpp/files/501090/emitting-nan-tst.cc.txt)

**Comment by abuchegger** [comment]
Same here. The problem is (as far as I could see from the source) that yaml-cpp uses the standard C++ streams for writing floating-point values (which have no defined behavior for nan/inf afaik) and does not treat these special cases separately.
