### ISSUE TITLE
key of a mapping node cannot be used in another mapping node, intentional?

### ISSUE THREAD

**Issue by tamaskenez** [jbeder/yaml-cpp#422]
Iterating over a `YAML::Node` yields keys of type `YAML::Node`. These keys cannot be used to index into another `YAML::Node` containing another mapping. Is this intentional?

Example:

Create two identical maps with `one: 1`:

                        YAML::Node map1, map2;
                        map1["one"] = "1";
                        map2["one"] = "1";

Take the first key of both:

                        auto k1 = map1.begin()->first;
                        auto k2 = map2.begin()->first;

They both contain the scalar string `one` which is correct.
Indexing `map1` with its own key yields the correct result: `1`

                        map1[k1] -> "1"

Indexing `map2` with the key of `map1` is an undefined:

                        map2[k1] -> ""

Taking the content is correct:

                        map2[k1.as<string>()] -> "1"

**Comment by jbeder** [comment]
Yes, that's intentional. Nodes have identity, and so the two nodes you're creating are equal, but not identical.
