### ISSUE TITLE
Exception for missing value is non-descriptive

### ISSUE THREAD

**Issue by joseph-ireland** [jbeder/yaml-cpp#423]
Using the example given in the tutorial: 

``` c++
YAML::Node config = YAML::LoadFile("config.yaml");

if (config["lastLogin"]) {
  std::cout << "Last logged in: " << config["lastLogin"].as<DateTime>() << "\n";
}

const std::string username = config["username"].as<std::string>();
const std::string password = config["password"].as<std::string>();
login(username, password);
config["lastLogin"] = getCurrentDateTime();

std::ofstream fout("config.yaml");
fout << config;
```

and the following YAML file:

``` yaml
usernaem: "user" # typo in key
password: "password
```

generates the exception 

> terminate called after throwing an instance of 'YAML::InvalidNode'
>  what():  invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa

Given any half-complex setup, this is impossible to debug without pulling up GDB, so all code is filled with manual error-checking for every field.

My suggestion given the current API would be to just add an stl-style `YAML::Node at(T key)`, which throws on failure, allowing the error to contain the key (at least in the case of string/int), and the Mark() for the parent node.

**Comment by jbeder** [comment]
Yeah, this error message isn't great. I think an alternate solution would be to store the path that you're looking up and then say something like:

    node with path "username" is invalid

Would that help?

**Comment by joseph-ireland** [comment]
that would be good too. I looked at the issue history before, and I saw that you didn't want to do that, that, but, thinking about it, many of the arguments in that issue would apply to an `.at()` function anyway, (i.e. large keys, keys that are other complex objects could be hard to print).

However, there would be slightly more complexity, since you would have to implement chaining,
i.e. with the trivial implementation, `config["missing key"]["username"].as<string>();` would follow down to the bottom node and say "password" is invalid, whereas `config.at("missing key").at("username") would throw straight away with the right error.

**Comment by joseph-ireland** [comment]
also, as an aside, (probably should have its own issue) it would be nice to have filename in the exception, then I could get rid of all my error-checking code and just rely on the exceptions.

**Comment by joseph-ireland** [comment]
actually, just storing the first missing key,and passing it on to subsequent nodes would be good enough, would be nice to chain it though.

**Comment by leni536** [comment]
It would be nice if at least the InvalidNode exception got constructed with a Mark closest to the problem. It would require Zombie nodes to have marks. But yeah, if InvalidNode contained the key in some form it would be even better.
