### ISSUE TITLE
YAML::Emitter Node output fails to suffix a newline

### ISSUE THREAD

**Issue by dooglio** [jbeder/yaml-cpp#428]
Consider the following code:
```
    YAML::Node node;
    // Add lots of stuff to node

    YAML::Emitter emitter;
    emitter.SetIndent( 4 );
    emitter.SetMapFormat( YAML::Flow );
    emitter
        << YAML::Comment("My Header Comment")
        << node
        << YAML::Comment("vim: ts=4 sw=4 et");
```

The output should add a newline between the last output line of `node` and the ending comment. However, the output looks more like this:
```
# My Header Comment
...
native_transport_port: 9042  # vim: ts=4 sw=4 et
```

So it seems that the last output line of a node does not get an ending newline in the output stream.

**Comment by jbeder** [comment]
If you want a newline, you can explicitly add a newline with `YAML::Newline`. yaml-cpp doesn't add a newline automatically because you might not want it.

**Comment by dooglio** [comment]
Thank you for your fast response!

I assumed (incorrectly) that newlines would be added automatically. Of course, all of the examples in your docs lead me to believe newlines would be suffixed automatically:

https://github.com/jbeder/yaml-cpp/wiki/How-To-Emit-YAML

Yes I realize that I'm streaming a node into the Emitter, but this behavior is not obvious, I think.

Would you mind updating your docs to cover this case? That way people like me won't open up issues that aren't issues. :-)
