### ISSUE TITLE
Ubuntu 16.04 still uses 0.5.2, which isn't compatible with the default g++-5 compiler

### ISSUE THREAD

**Issue by pbeeson** [jbeder/yaml-cpp#442]
Is there anything you can do to try to bump the default Ubuntu debian package to not throw compile warnings when using remove()?

```
/usr/include/yaml-cpp/node/detail/impl.h:136:15: error: ‘equals’ was not declared in this scope
     if (equals(*it->first, key, pMemory)) {
```

**Comment by jbeder** [comment]
I have no control over what gets released in Ubuntu packages. Perhaps ask them?
