### ISSUE TITLE
x64 warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data

### ISSUE THREAD

**Issue by ukoloff** [jbeder/yaml-cpp#448]
When compiling with [MSVC on x64](https://ci.appveyor.com/project/ukoloff/nf4s/build/1.0.16-yaml/job/dhx08p25gdd526y6) I get two warnings:

yaml-cpp\src\emitter.cpp(703): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
yaml-cpp\src\emitter.cpp(879): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data

On [x86](https://ci.appveyor.com/project/ukoloff/nf4s/build/1.0.16-yaml/job/bkbppxvby8ntllh1) no warnings.

May be some type cast should be applyed?

**Comment by jbeder** [comment]
Feel free to submit a PR.

**Comment by tambry** [comment]
Should be fixed now, can probably be closed.

**Comment by ukoloff** [comment]
Confirmed: warnings disappeared.
