### ISSUE TITLE
How to merge node

### ISSUE THREAD

**Issue by sunshichao520** [jbeder/yaml-cpp#454]
I have two node object, like this:
person:
   name: a
person:
   age:18
How to merge it, the result like this:
person:
   name: a
   age:18
the above is a example, ths node size do not kown and the node depth do not kown, how to merge two node?

**Comment by jbeder** [comment]
Please ask on [stackoverflow.com](http://stackoverflow.com) and tag it `yaml-cpp`.

**Comment by sunshichao520** [comment]
what I want to say is that, yaml node have:

```
 const Node operator[](const Node& key) const; 
 Node operator[](const Node& key);
```

but there are not have:
  `Node& operator[](const Node& key);`
or
 `Node* operator[](const Node& key);`

so I can operate sub_node. like this:
```
Node a["test1"]["test2"]["test3"] = "test";
Node& b = a["test1"];
b["test2"] = Load("{other: nothing}");
```
Can you provider it? thanks

**Comment by jbeder** [comment]
The first line of your code wouldn't compile even if there were new functions. 

What are you looking for? Node is a reference type, so even if you have a Node by value, it will operate on shared underlying data.

**Comment by sunshichao520** [comment]
The first line is data type, just a example.
Say my problem:
two file:
a.yaml
```
test1:
  test2:
    test3:
      test4: a;
```
b.yaml
```
test1:
  test2:
    test3:
      test5: b;
```

then I load yaml
```
YAML::Node a = YAML::LoadFile("a.yaml");
YAML::Node b = YAML::LoadFile("b.yaml");
```
I want to merge it, the result is:
```
test1:
  test2:
    test3:
      test4: a;
      test5: b;
```
So I need to get sub node of node a and b
```
Node& sub_a = a["test1"]["test2"]["test3"]; // depth are not konw, so I need to find the last different positon
Node& sub_b = a["test1"]["test2"]["test3"];
sub_a["test5"] = sub_b["test5"];
```
when using reference type, I got a error: "invalid initialization of non-const reference of type 'YAML::Node&' from an rvalue of type 'YAML::Node' ",  but I can not use const, I need to change value of node_a. So I hope you can privide:
```
Node& operator[](const Node& key);
or
Node* operator[](const Node& key);
```

**Comment by sunshichao520** [comment]
Thanks for your help, I found the way to solve the problem, by add the code:
`YAML::Node& non_const_node = const_cast<YAML::Node&>(node_a);`

**Comment by jbeder** [comment]
OK. Note that you don't need a C++ reference, since `YAML::Node` is a reference type.

**Comment by sunshichao520** [comment]
Yes. But when node is function parameter, it is no longer a reference. So I can not do it. Thanks again!
