### ISSUE TITLE
Build and deploy procedure and header files

### ISSUE THREAD

**Issue by HerbertKoelman** [jbeder/yaml-cpp#455]
Hello,

I've downloaded the latest version from the master branch.

I then did follow the instruction found here:
1. create a build directory
2. use cmake (on AIX) to generate needed scripts to compile and install the library (`cmake ...`)
3. run make (in build directory)

All seems well, a libyaml.a file was produced in the build directory. I would say 'so far, so good'.

Here is my question: **where are the header files to use the library ?**

The include directory only contains a file yaml.h.

Where are the rest ?

**Comment by jbeder** [comment]
The include directory:

https://github.com/jbeder/yaml-cpp/tree/master/include

**Comment by HerbertKoelman** [comment]
Thanks, my mistake (I was looking in the wrong directory).

Regards
