### ISSUE TITLE
Symbol lookup error

### ISSUE THREAD

**Issue by renkun-ken** [jbeder/yaml-cpp#484]
I'm under Ubuntu 16.04.2 LTS and my IME suddenly stop working and its deployment app says 

```
rime_deployer: symbol lookup error: /usr/lib/librime.so.1: undefined symbol: _ZN4YAML6detail9node_data12empty_scalarB5cxx11E
```

which seems to be part of `yaml-cpp` as noted in https://github.com/rime/ibus-rime/issues/26. I tried the PPA (https://launchpad.net/~winterheart/+archive/ubuntu/openxcom) provided at https://bugs.launchpad.net/ubuntu/+source/yaml-cpp/+bug/1646914 but it does not work. Is there anything I can do about this?

**Comment by winterheart** [comment]
Hello.
It's little late to answer, but...
It seems your ibus-rime uses old version of yaml-cpp (probably 0.5.0?), but you have newer version from official Ubuntu's repository. You'll need to rebuild ibus-rime against 0.5.3 or ask ppa owners to do it for you.

**Comment by renkun-ken** [comment]
Thanks!
