### ISSUE TITLE
`Scanner::EnsureTokensInQueue` contains infinite loop

### ISSUE THREAD

**Issue by HongxuChen** [jbeder/yaml-cpp#499]
Many cases will cause while loop inside `Scanner::EnsureTokensInQueue` to fail to break out. Two special example are the inputs `[:` whose byte representation is 23354, and `{:`, whose byte representation is 31546.

Several other cases can be seen from [timeouts](https://gist.github.com/HongxuChen/2c40c13a9b09d11bead9040b8afe8177#file-timeouts) (1 case per line), which is generated by `t2()` in [gen.py](https://gist.github.com/HongxuChen/2c40c13a9b09d11bead9040b8afe8177#file-gen-py).

**Comment by djpeaco** [comment]
We encounter this bug frequently. For example, if we pass some yaml through the shell and don't quote it properly, the parser will hang rather than failing with an error:
```
$ my_app --config "{foo: bar}"  # This works
$ my_app --config {foo: bar}    # Oops, this calls YAML::Load("{foo:") which hangs forever
```

**Comment by dominiakm** [comment]
Please note that this is more dangerous than a simple infinite loop: each pass of this loop allocates new memory.
This eventually leads to the process being killed by OOM killer.
This can lead to a DoS attack on not only the application using this library, but also the entire system (due to memory exhaustion).

**Comment by dende** [comment]
this bug is easily triggered with a simple libfuzzer fuzztarget btw

```
#include <string>
#include <stdint.h>
#include <iostream>
#include "yaml-cpp/yaml.h"

extern "C" int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size) {
   try {
       if (Size > 0) {
       YAML::Node doc = YAML::Load(std::string(reinterpret_cast<const char *>(Data), Size));
       }
   } catch (const YAML::Exception& e) {
   } catch (const std::exception& e) { }
 return 0;  // Non-zero return values are reserved for future use.
}
```

And since this bug is so easy to trigger it prevents yaml-cpp from being fuzzed any further

**Comment by Yankes** [comment]
@jbeder Possible fix look like:
```cpp
inline const RegEx& PlainScalarInFlow() {
  static const RegEx e =
      !(BlankOrBreak() || RegEx("?,[]{}#&*!|>\'\"%@`", REGEX_OR) ||
        (RegEx("-:", REGEX_OR) + (Blank() || RegEx()))); //here was added handling of EOF
  return e;
}
```
This bug look like that `PlainScalarInFlow` find scalar but other part of code do not see it as scalar and code go back to first check and we have infinite loop.

**Comment by Yankes** [comment]
fixed in https://github.com/jbeder/yaml-cpp/commit/f05b2577ade38f2e24f5c2cc298230d69b4010a4

**Comment by jbeder** [comment]
Thanks @Yankes, I'll close this.

Others: the original examples posted all parse with errors (correctly) now instead of hanging. If there still is a related issue, please open a new bug with examples.
