### ISSUE TITLE
I can edit node in function without passing by reference

### ISSUE THREAD

**Issue by benlindsay** [jbeder/yaml-cpp#510]
I have a situation where I want to look through every single key and value in a `YAML::Node` and possibly edit each one. I found it surprising that I can do that using a recursive function that accepts a `YAML::Node` argument rather than `YAML::Node&`. Here's an example:

```
#include <iostream>
#include "yaml-cpp/yaml.h"

std::string edit_string(std::string str) {
  return str + "_edited";
}

void iterate_node(YAML::Node node) {
  if (node.IsNull()) {
    return;
  }
  if (node.IsScalar()) {
    node = edit_string(node.as<std::string>());
  }
  else if (node.IsMap()) {
    for (YAML::iterator it = node.begin(); it != node.end(); ++it) {
      iterate_node(it->first);
      iterate_node(it->second);
    }
  }
  else if (node.IsSequence()) {
    for (std::size_t i=0; i < node.size(); i++) {
      iterate_node(node[i]);
    }
  }
}

int main(int argc, const char *argv[])
{
  YAML::Node input = YAML::Load("{sequence: [foo: bar, baz, qux]}");
  std::cout << input << std::endl;
  iterate_node(input);
  std::cout << input << std::endl;
  return 0;
}
```

Running this code will output the following:

```
{sequence: [{foo: bar}, baz, qux]}
{sequence_edited: [{foo_edited: bar_edited}, baz_edited, qux_edited]}
```

Is this expected behavior? I would have thought that any changes made to `input` in the `iterate_node` function would be local to `iterate_node`, but I'm able to make changes that last outside the scope of the function at all depths of the structure. In fact, if I try to change the argument of `iterate_node` to `YAML::Node& node`, I get a compile error like this:

```
spike/byref3.cpp: In function ‘void iterate_node(YAML::Node&)’:
spike/byref3.cpp:28:27: error: invalid initialization of non-const reference of type ‘YAML::Node&’ from an rvalue of type ‘YAML::Node’
       iterate_node(node[i]);
                           ^
spike/byref3.cpp:13:6: note:   initializing argument 1 of ‘void iterate_node(YAML::Node&)’
 void iterate_node(YAML::Node& node) {
      ^
make: *** [byref3] Error 1
```

It seems like everything works fine as long as I leave off the `&`, but I'm curious to know what I'm missing and why I have what seems like a magical power to make lasting changes without passing any variables by reference or pointer.

**Comment by jbeder** [comment]
Yes, this is workign as intended - `YAML::Node` is a reference type, not a value type.

**Comment by benlindsay** [comment]
gotcha, thanks!
