### ISSUE TITLE
Emit YAML::NODE   is this supposed to work? if so, it doesn'T

### ISSUE THREAD

**Issue by yamcenutzer** [jbeder/yaml-cpp#522]
ostream << YAML:NODe only works for trivial basic NOdes.
However if you do have a nested sequence/map, everything is broken.
The example below doesn't work.

 In theory, I would like to do something like:
`theConfig = YAML::LoadFile(""xx")
`
and later:

```
ofstream fout(configFile + ".saved");
fout << theConfig;

```

Example yaml file:
```
formatVersion:                   0.9.2.1
fileVersion:      2017-08-11 19:01:00
reportTo:                  bla
reportFormat:           foo   
ResetFailedAgent:          no
resetFailedAgentsMethod:   hammer
heartbeatMaxAgeBeforeFail: 10
# add agents below
agents: [
            {
                name: self4,
                ip:   127.0.0.1,
                port: 23456
            },
            {
                name: self6,
                ip:   ::1,
                port: 23456
            },
            {
                name: a1,
                ip:   19.158.19.1,
                port: 23456
            },
            {
                name: a2,
                ip:   19.158.19.2,
                port: 23456
            },
            {
                name: a3,
                ip:   19.158.19.3,
                port: 23456
            }
        ]



```

**Comment by jbeder** [comment]
Could you post the version of yaml-cpp you're using, and also the output you're seeing? When I try your example, it looks correct.

**Comment by yamcenutzer** [comment]
ON windows I'm using the current vpkg port called .5.4-rc-1 and on linux 0.5.3.
heres's input:
```
formatVersion:                   0.9.2.1
fileVersion:      2017-08-11 19:01:00
reportTo:                  
reportFormat:              
ResetFailedAgent:          no
resetFailedAgentsMethod:   
heartbeatMaxAgeBeforeFail: 10
# add agents below
agents: [
            {
                name: self4,
                ip:   127.0.0.1,
                port: 23456
            },
            {
                name: self6,
                ip:   ::1,
                port: 23456
            },
            {
                name: a1,
                ip:   19.158.19.1,
                port: 23456
            },
            {
                name: a2,
                ip:   19.158.19.2,
                port: 23456
            },
            {
                name: a3,
                ip:   19.158.19.3,
                port: 23456
            }
        ]

```
and here the output:
```
version: ~
heartbeatMaxAgeBeforeFail: &1 [{port: 23456, name: self4, ip: 127.0.0.1}, {port: 23456, name: self6, ip: ::1}, {ip: 19.158.19.1, port: 23456, name: a1}, {port: 23456, name: a2, ip: 19.158.19.2}, {port: 23456, name: a3, ip: 19.158.19.3}]
reportTo: ~
reportFormat: no
formatVersion: 0.9.2.1
agents: *1
resetFailedAgentsMethod: 10
fileVersion: 2017-08-11 19:01:00
ResetFailedAgent: ~
```

**Comment by yamcenutzer** [comment]
Update:
i wrote a simple program that does nothng else, read a yaml file and write it out again.
That seems to in fact work.
However, the original prog, where I also do real work inbetween, doesn't.
So it seems like therre is something else going on, other libs, storage issues...
So even in the 'real' prog if I immeadiatly write out after reading/parsing it goes wrong.
I need to look further if I can determine the exact cause of this.

**Comment by LucaCerina** [comment]
I had a similar issue copying some maps temporarily, changing their content and then copying them back to the original node.

I guess it depends from the shallow copy nature of the nodes in # 516 . I solved it using 'temp_node = YAML::Clone(original_node)' before doing anything on that.

**Comment by jbeder** [comment]
I'm going to close this issue, but if you feel there's a bug, please re-open and post a minimal example that demonstrates the issue.
