### ISSUE TITLE
libc++ 5.0.0 will have auto_ptr removed for C++17. Already fixed in master, but not released yet.

### ISSUE THREAD

**Issue by EdSchouten** [jbeder/yaml-cpp#523]
The latest version of yaml-cpp makes use of `auto_ptr` in its public header files (`emitter.h` and `parser.h`). The upcoming release of libc++, version 5.0.0, will have `auto_ptr` removed when building for C++17. This is problematic, as it means yaml-cpp will then no longer be usable by programs/libraries that are built for C++17.

This issue has already been fixed in master, as it uses `unique_ptr` exclusively. Considering that the last release of yaml-cpp is already 1.5 years old, could we please cut a new release to ensure this gets rolled out?

**Comment by EdSchouten** [comment]
For distros/operating systems/package managers willing to distribute a copy of the latest release of yaml-cpp that does work well with C++17, this patch should do it:

https://github.com/NuxiNL/cloudabi-ports/blob/master/packages/yaml-cpp/patch-auto_ptr-c%2B%2B17

**Comment by jbeder** [comment]
Just released [yaml-cpp-0.6.0](https://github.com/jbeder/yaml-cpp/releases/tag/yaml-cpp-0.6.0)
