### ISSUE TITLE
YAML-CPP without Boost.

### ISSUE THREAD

**Issue by Haider-BA** [jbeder/yaml-cpp#525]
Is yaml-cpp is available without boost libraries? If not, until when it will be?

**Comment by vyp** [comment]
#342

**Comment by emlai** [comment]
#342 was merged almost a year and nine months ago. Could you make a new release so I can start using this library?

**Comment by vyp** [comment]
@emlai #415

**Comment by kramasamy** [comment]
It will be nice to make a release without boost.

**Comment by nerzhul** [comment]
@jbeder please release this library without boost, it's anoying to take 4h to compile boost just because the actual library uses it... take some time to release a 0.6 with that for C++11 compilers, which are used everytime this days... many are C++17 compliant

**Comment by vks** [comment]
> it's anoying to take 4h to compile boost just because the actual library uses it...

You don't have to compile all of boost for use with yaml-cpp.

**Comment by nerzhul** [comment]
@vks it's how the freebsd ports tree works, there is no boost flavour.

**Comment by hobbes1069** [comment]
It would have been better to make this optional. This change broke ABI compatibility on EPEL 7 which should not happen for a patch level update (0.5.1->0.5.3).

**Comment by jbeder** [comment]
Just released [yaml-cpp-0.6.0](https://github.com/jbeder/yaml-cpp/releases/tag/yaml-cpp-0.6.0)
