### ISSUE TITLE
Possibility to read environment variables

### ISSUE THREAD

**Issue by samssann** [jbeder/yaml-cpp#527]
config.yaml:
home: $HOME

main.cpp:
int main() {
  YAML::Node config = YAML::LoadFile("config.yaml");
  const std::string home = config["home"].as<std::string>();
  std::cout << home << std::endl;
}

result => /path/to/home/

Could this be a possible enhancement?

**Comment by jbeder** [comment]
It does not; and it's unlikely we'll support this directly (although it's easy to post-process nodes yourself if you like).
