### ISSUE TITLE
 Different sha512sums value in version 0.5.3

### ISSUE THREAD

**Issue by rgdoliveira** [jbeder/yaml-cpp#535]
Alpine Linux builds yaml-cpp and it downloads the 0.5.3 source from github

We are rebuilding all the Alpine packages for 3.7 release but yaml-cpp failed to build when comparing the sha512sums. It was before:
sha512sums="cb11acccc5261e4513b597becf6be5d7fef05ef89a11eda3fc7db9e513adf953a2ec9c1bf70b91277076d793f0c65a496c7243d9b4a4240623e5f7034f8d4ad3  yaml-cpp-0.5.3.tar.gz"

And now:
sha512sums="fb8683e2b9847dac7e222185816637ccbec3b429abe8965169349ca9a10983692f1d78fd03c522490efd29962157cd3df25cd4f2e2fec2149d28d0df8e136dd3  yaml-cpp-0.5.3.tar.gz"

Does this tar.gz got any changes or it was uploaded again (or something like that)?

**Comment by jbeder** [comment]
Shouldn't have; github generates those tarballs, so maybe file an bug with them?
