### ISSUE TITLE
Do not install Google {Mock,Test}

### ISSUE THREAD

**Issue by mwoehlke-kitware** [jbeder/yaml-cpp#539]
[Fletch](https://github.com/kitware/fletch) is building yaml-cpp as part of a suite of third-party libraries, including Google Test. Current master of yaml-cpp is also installing Google Mock and Google Test, which results in a conflict with the separately built and installed Google Test. Since these are not run-time dependencies of yaml-cpp, they should not be installed. (Preferably, there should also be an option to disable building the tests — and Google {Mock,Test} — entirely.)

**Comment by just6979** [comment]
`option(YAML_CPP_BUILD_TOOLS "Enable testing and parse tools" ON)` <- set this to off and it won't build/install the test stuff

**Comment by mwoehlke-kitware** [comment]
That's... not at all obvious. Are the tests coupled to the tools, or could they be guarded by an option with a more obvious name?

At any rate, Google {Mock,Test} should not be installed either way. (I believe latest upstream supports this; it may be necessary to update yaml-cpp's copy of Google Test to fix this properly.)

**Comment by just6979** [comment]
The option could have a different name, and could default to off. Why don't you submit a patch with one or both of those changes and see what happens?

**Comment by mwoehlke-kitware** [comment]
> Why don't you submit a patch with one or both of those changes and see what happens?

→ #541.

**Comment by jbeder** [comment]
Is the question here to build the tests by default, or to install them?

It seems reasonable not to install anything test/mock related.

**Comment by mwoehlke-kitware** [comment]
*Building* by default was meant as an aside (which is addressed by #541). Google {Mock,Test} also should not be *installed*, ever (even when tests are built). The latest upstream Google Test supports this, but not I think the version currently in yaml-cpp, so the first step would be to update the version of Google Test in yaml-cpp.

**Comment by jbeder** [comment]
SG. I commented on #541, and happy to accept a PR that avoids installing gmock/test.

**Comment by nerzhul** [comment]
@jbeder can this be fixed and a release happen ? i will be happy to update the FreeBSD port to make boost shit disappear from my poudriere :)

**Comment by vks** [comment]
As a workaround, I believe you can just use `cmake -DYAML_CPP_BUILD_TOOLS=OFF` when building yaml-cpp.

**Comment by ryandesign** [comment]
> As a workaround, I believe you can just use `cmake -DYAML_CPP_BUILD_TOOLS=OFF` when building yaml-cpp.

That doesn't do it, but `cmake -DYAML_CPP_BUILD_TESTS=OFF` does.

**Comment by jasonszang** [comment]
Changing from

> add_subdirectory(gtest-1.8.0)

to 

> add_subdirectory(gtest-1.8.0 EXCLUDE_FROM_ALL)

worked for me, but I'm not sure if this applies to ancient versions of cmake(I'm using 3.10.2). I tried to google but it looks like that EXCLUDE_FROM_ALL vs install is, or was, an undefined behaviour of some sort? Could anyone familiar with CMake kindly explain?
