### ISSUE TITLE
Failed to install shared library build

### ISSUE THREAD

**Issue by yhan-argo** [jbeder/yaml-cpp#543]
tried to install as shared libray,

mkdir build
cd build 
cmake .. -DBUILD_SHARED_LIBS=ON
make
make install 
----------- Error message --------------------

Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libyaml-cpp.so.0.5.3
CMake Error at cmake_install.cmake:48 (file):
  file INSTALL cannot copy file
  "/home/yhan/3rd_party_libs/yaml-cpp-release-0.5.3/build/libyaml-cpp.so.0.5.3"
  to "/usr/local/lib/libyaml-cpp.so.0.5.3".

Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by caryoscelus** [comment]
Are you sure you have permissions to write in `/usr/local`? Maybe you should run `sudo make install` instead?

**Comment by yhan-argo** [comment]
no need
