### ISSUE TITLE
Documentation does not speak about  EmitterStyle

### ISSUE THREAD

**Issue by YannLePoul** [jbeder/yaml-cpp#549]
I spent some time understanding why when creating a sequence, the yaml emitter was creating:
 ```
- 1
- 2
- 3
```
instead of `[1, 2, 3]`
When browsing the source code, I discovered the `EmitterStyle::Flow` and  `EmitterStyle::Block`. Would it be possible to mention those somewhere in the tutorials ?

Thanks

**Comment by jbeder** [comment]
See the section [Using Manipulators](https://github.com/jbeder/yaml-cpp/wiki/How-To-Emit-YAML#using-manipulators) in the documentation.
