### ISSUE TITLE
Emitting strings with special characters as value

### ISSUE THREAD

**Issue by arihantb2** [jbeder/yaml-cpp#550]
I am trying to emit a key value pair onto a yaml with special characters in the value field. For example,
```
key: va:lu:e
```
This is not supported in the current yaml standards beacuse **:** is a special character. A workaround for this is to surround the value containing special characters with quotes. As in,
```
key: "va:lu:e"
```
Is there a way I can emit a value with quotes around it?

**Comment by caryoscelus** [comment]
Hmm, when i am emitting such strings, they're quoted automatically.

**Comment by jbeder** [comment]
Yep, that's right; yaml-cpp detects the special characters and quotes them automatically.
