### ISSUE TITLE
Checksum for release 0.5.3 has changed

### ISSUE THREAD

**Issue by carrotIndustries** [jbeder/yaml-cpp#551]
When trying to rebuild the arch linux package for yaml-cpp I noticed that the the checksum for https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.5.3.tar.gz has changed. The sha512 sum according to the arch linux PKGBUILD is `5ed15fee3c6455c08e6bd8f74256b230f274ef18f8e144491e940640e41626517c7eaaf4a1f380c4179066a2a757c8a0f61878df9dc3caa15e37c4954be47fe0`

What's going on?

**Comment by jbeder** [comment]
I don't know - nothing has changed, as far as I know. Github manages those tarballs. Out of curiosity, when was that hash in arch linux computed?

**Comment by jbeder** [comment]
Gotcha. That seems kinda shady of github. So everything's OK?

**Comment by ryandesign** [comment]
Many of GitHub's automatically-generated tarballs changed after GitHub updated to a version of git that included [this commit](https://github.com/git/git/commit/22f0dcd9634a818a0c83f23ea1a48f2d620c0546). Here is the [MacPorts project's ticket](https://trac.macports.org/ticket/54839) tracking updating all the ports affected by that.
