### ISSUE TITLE
Update googletest to Fix Build Error [Visual Studio 2017]

### ISSUE THREAD

**Issue by coder0xff** [jbeder/yaml-cpp#553]
I was getting warnings, which were treated as errors.

> C:\Users\coder\Desktop\yaml-cpp\test\gtest-1.8.0\googletest\include\gtest/internal/gtest-port.h(996): error C2220: warning treated as error - no 'object' file generated

> C:\Users\coder\Desktop\yaml-cpp\test\gtest-1.8.0\googletest\include\gtest/internal/gtest-port.h(996): warning C4996: 'std::tr1': warning STL4002: The non-Standard std::tr1 namespace and TR1-only machinery are deprecated and will be REMOVED. You can define _SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING to acknowledge that you have received this warning.

It's been fixed in gtest already, but was reported here: https://github.com/google/googletest/issues/1373. I downloaded the commit currently on master https://github.com/google/googletest/commit/718fd88d8f145c63b8cc134cf8fed92743cc112f and dropped it into yaml-cpp and it worked fine.

**Comment by tambry** [comment]
Also encountered this after upgrading my compiler. Tons of warnings now, which are all treated as errors.

The workaround is to add:

    set(YAML_CPP_BUILD_TESTS OFF CACHE BOOL "Build yamp-cpp tests")
