### ISSUE TITLE
CMakeLists.txt has wrong YAML_CPP_VERSION_PATCH value for tag 0.6.1

### ISSUE THREAD

**Issue by avostrik** [jbeder/yaml-cpp#560]
Shall be:

--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -28,7 +28,7 @@ project(YAML_CPP)
 
 set(YAML_CPP_VERSION_MAJOR "0")
 set(YAML_CPP_VERSION_MINOR "6")
-set(YAML_CPP_VERSION_PATCH "0")
+set(YAML_CPP_VERSION_PATCH "1")

**Comment by jbeder** [comment]
Fixed https://github.com/jbeder/yaml-cpp/commit/562aefc114938e388457e6a531ed7b54d9dc1b62

Updating to 0.6.2 to make a new release so they're consistent.
