### ISSUE TITLE
would you please use '> >' instead of '>>'

### ISSUE THREAD

**Issue by heretic1993** [jbeder/yaml-cpp#569]
the compile keep emitting errors on ">>" problems on Mac

**Comment by jbeder** [comment]
What compiler, and how are you compiling the library?

This has been standard C++ since C++11, and all major compilers support it.

**Comment by heretic1993** [comment]
I used Apple Clang 8.1.0.8020038 on my mac. 
I just compiled some packages of ROS using catkin_make, and they require yaml-cpp.
It throws out errors when it meets something like:

std::vector<std::pair<node*, node*>> node_map;

**Comment by jbeder** [comment]
I'm not sure what version 8.1 means (it looks like Clang is currently at v6?), but it definitely supports C++11:

https://clang.llvm.org/cxx_status.html

Be sure to pass `-std=c++11`.
