### ISSUE TITLE
Differentiating between an INT and a stringified INT

### ISSUE THREAD

**Issue by xguerin** [jbeder/yaml-cpp#572]
When parsing the following:

```yaml
key: "1000"
```

The node value trims the quote character, making it difficult to determine wether the value was a string or an integer. Is there a more appropriate way in the API to do that?

**Comment by jbeder** [comment]
`YAML::Node` has a `GetTag` function that returns the tag; this will be `!!str` for a quoted string, and otherwise `?` which means unspecified.

**Comment by KulaGGin** [comment]
It's Tag in the new versions: https://github.com/jbeder/yaml-cpp/blob/39f737443b05e4135e697cb91c2b7b18095acd53/docs/Breaking-Changes.md?plain=1#L44

**Comment by KulaGGin** [comment]
Also, it doesn't work out of the box. Had to change the function from:
```C++
inline void Node::Assign(const char* rhs) {
  EnsureNodeExists();
  m_pNode->set_scalar(rhs);
}
```
To:
```C++
inline void Node::Assign(const char* rhs) {
  EnsureNodeExists();
  m_pNode->set_scalar(rhs);
  m_pNode->set_tag("!!str");
}
```
