### ISSUE TITLE
Make customization through inheritance easier

### ISSUE THREAD

**Issue by drdavella** [jbeder/yaml-cpp#584]
I have a particular use case where it would be very useful to implement a custom subclass of `Node`. However, this is currently very difficult, or maybe impossible. At a minimum there are two things that would be extremely helpful:

* Change `private` members of `Node` to `protected` in order to facilitate inheritance
* Make `NodeBuilder` part of the public API to allow it to be inherited. In order for this to work, its `private` members would also need to become `protected`.

Is there any chance these changes are acceptable? If so, I may have a few spare cycles to submit a PR.

**Comment by jbeder** [comment]
Sorry, I don't think inheritance is the right way to go for customization. If there are particular things you'd like to do that you can't now, I'd rather address them.
