### ISSUE TITLE
Arduino implementation of YAML parser (and emitter)

### ISSUE THREAD

**Issue by scls19fr** [jbeder/yaml-cpp#592]
Hello,

https://cse.google.com/cse/publicurl?cx=008830049033802121810%3Azgsyidwem5w&q=json
shows that Arduino implementation of JSON parser exist.

We can found 
- https://github.com/bblanchon/ArduinoJson
- https://github.com/zserge/jsmn

Although I haven't been able to found YAML parser for Arduino

Is there a chance to have such a lib be implemented and tested on Arduino devices ?

Kind regards

**Comment by jbeder** [comment]
I haven't tested this on Arduino, but I don't see why it wouldn't work; it's intended to be cross-platform.

**Comment by kopierreko** [comment]
It can't work because you use exceptions and they aren't activated on uCs...

**Comment by kopierreko** [comment]
(I just tested on Teensy 3.6 / Arduino Uno)

**Comment by kopierreko** [comment]
It doesn't work because exceptions are deactivated on Arduino/Teensy

**Comment by kennethDow** [comment]
> It doesn't work because exceptions are deactivated on Arduino/Teensy

My elaborate guess would be, that some of the supported microcontrollers in arduino lack hardware implementation for exception handling.

**Comment by tobozo** [comment]
hi, 

maybe this library can help

https://github.com/tobozo/YAMLDuino
