### ISSUE TITLE
Access alias information after reading YAML document

### ISSUE THREAD

**Issue by eschnett** [jbeder/yaml-cpp#593]
I am reading YAML documents that use anchors and aliases. After reading such a document, `yaml-cpp` resolves the aliases, and I thus have no way of knowing whether a particular node was present directly in the YAML file or as alias, pointing to a certain anchor.

I am using YAML to represent a certain structure <https://github.com/eschnett/SimulationIO>, and thus need to know whether a node is an alias, and if so, to which node it points. It seems that `yaml-cpp` is preserving this information somehow, as emitting a read document has to correct alias information (with the anchors renamed, which is fine). I have not found a way to access this information via the API. Is there such a way? If not, can it be added? Or can you point me to what would need to be done to make this happen?

**Comment by jbeder** [comment]
I don't think it's actually preserved; I think it makes a new alias/anchor group and chooses based on what it sees first when it writes the node out. Is this good enough for your use case?

**Comment by eschnett** [comment]
Yes, this happens to be good enough.

**Comment by eschnett** [comment]
The current API isn't quit sufficient, though; I need to be able to associate other information with YAML nodes, which I then need to retrieve for an alias. For example, using nodes as keys in a C++ map would be sufficient. Can that be added? This would require either an `<=` operator or a hash function.

**Comment by jbeder** [comment]
Nodes are mutable, which makes me uncomfortable giving them a hash function.

**Comment by eschnett** [comment]
What about `<=` then? They already have an `==` operator.
