### ISSUE TITLE
Documentation On Using This With Pointers (if that is possible)?

### ISSUE THREAD

**Issue by ryanzec** [jbeder/yaml-cpp#596]
So far using this library with the documentation provide has been a very nice experience however there is one thing I want to test before moving forward with using this library in my project and that is using this with pointers.

For example say I have this struct:

```cpp
struct Inventory {
  float maximumWeight;
  std::vector<InventoryItem*> items;
};
```

I want to be able to create an encoder / decoder for this struct however everything I have tried just results in errors (and maybe it is just me as my C++ experience it limited). The reason for want to work with pointer is that I will have data structures that will need to use pointer because of either needing that data to be accessible outside the scope it is created in or because because the data it going to be too large for the stack.

I am not sure if it is or is not possible to create encoders / decoders for struct that have pointers or not but if it is, I think that would be a nice addition to the documentation (it might also be nice to have documentation about outputting very large files).

**Comment by ryanzec** [comment]
For a little more context, this is my code:

```cpp
struct InventoryItem {
  std::string name;
  int baseValue;
  float weight;
};

struct Inventory {
  float maximumWeight;
  std::vector<InventoryItem*> items;
};

namespace YAML {
template <>
struct convert<InventoryItem*> {
  static Node encode(const InventoryItem* inventoryItem) {
    Node node;

    node["name"] = inventoryItem->name;
    node["baseValue"] = inventoryItem->baseValue;
    node["weight"] = inventoryItem->weight;

    return node;
  }

  static bool decode(const Node& node, InventoryItem* inventoryItem) {
    // @todo validation
    inventoryItem->name = node["name"].as<std::string>();
    inventoryItem->baseValue = node["baseValue"].as<int>();
    inventoryItem->weight = node["weight"].as<float>();

    return true;
  }
};

template <>
struct convert<Inventory> {
  static Node encode(const Inventory& inventory) {
    Node node;

    node["maximumWeight"] = inventory.maximumWeight;
    node["items"] = inventory.items;

    return node;
  }

  static bool decode(const Node& node, Inventory& inventory) {
    // @todo validation
    inventory.maximumWeight = node["maximumWeight"].as<float>();
    inventory.items = node["items"].as<std::vector<InventoryItem*>>();

    return true;
  }
};
}
```

The error I am getting is:

```impl.h(123): error C4700: uninitialized local variable 't' used```

Which is referencing the last if statement in this code block:

```cpp
template <typename T>
struct as_if<T, void> {
  explicit as_if(const Node& node_) : node(node_) {}
  const Node& node;

  T operator()() const {
    if (!node.m_pNode)
      throw TypedBadConversion<T>(node.Mark());

    T t;
    if (convert<T>::decode(node, t)) // NOTE: THIS IS THE LINE THE COMPILER ERROR IS REFERENCING
      return t;
    throw TypedBadConversion<T>(node.Mark());
  }
};
```

**Comment by KitsuneRal** [comment]
That doesn't seem to have anything to do with yaml-cpp; you omitted the reference in `decode<InventoryItem*>` parameter, hence the consequences. I guess further explanations better be requested at StackOverflow.

**Comment by ryanzec** [comment]
@KitsuneRal So I am not exactly sure whay you mean by me omitting the reference in decode (i am not sure what to change). I do have a stackoverflow post if you want to provide some more detail there: https://stackoverflow.com/questions/50807707/yaml-cpp-encoding-decoding-pointers

**Comment by ryanzec** [comment]
I got the answer I was looking for from gamedev.net and probably what @KitsuneRal was referring to. In decode I needed to use `InventoryItem*& inventoryItem` which I did try before however the piece I was missing was that in this case `inventoryItem` is uninitialized so I also need to add:

```cpp
inventoryItem = new InventoryItem();﻿
```

At the beginning of the decode for `InventoryItem` and everything worked.
