### ISSUE TITLE
Performance Issue In Debug Mode (Default Visual Studio Settings)

### ISSUE THREAD

**Issue by ryanzec** [jbeder/yaml-cpp#598]
**UPDATE**

The ultimate issue seems to be running with the default Visual Studio Debug Mode settings. Running the code in debug mode vs relase mode looks like this:

Stat | Debug Mode | Release Mode
------------ | ------------- | -------------
Save Time | ~7 seconds | ~0.15 seconds
Memory usage | ~85MB | ~15MB

I thought it was good practice to always run code in debug mode when writing code however this kinda of performance loss seems bad. I am not sure if there are some tweaks to I can make to the debug mode settings to prevent this kinda of performance hit while still retaining a lot of the benefits of debug mode.

---

So I was testing to see what the performance might be for slightly larger files.

Here is my code:

```cpp
static void saveGame() {
  Player newPlayer = Player();
  newPlayer.name = "new player";
  newPlayer.maximumHealth= 1000;
  newPlayer.currentHealth = 1;

  Inventory newInventory;
  newInventory.maximumWeight = -10.9f;

  for (int z = 0; z < 10000; z++) {
    InventoryItem* newItem = new InventoryItem();
    newItem->name = "Stone";
    newItem->baseValue = 1;
    newItem->weight = 0.1f;

    newInventory.items.push_back(newItem);
  }

  YAML::Node newSavedGame;
  newSavedGame["player"] = newPlayer;
  newSavedGame["inventory"] = newInventory;

  Timer timer = Timer();
  YamlUtility::saveAsFile(newSavedGame, "utilitySave.yaml");
  timer.setEnd();

  std::cout << "Saving file took: " << timer << std::endl;
};
```

So there are 2 area of performance that seem worrisome to me.

## Memory

By application by default loads up with 22MB on memory usage.

If I call the `saveGame()` method with the YAML code commented out it goes up to 23MB.

With the YAML code (but not the saving code), it jumps to 108MB. This seems a bit weird to me. I can image the memory would go up however if the data itself only increases memory by < 1MB, why would the YAML code increase it by an additional 85MB?

## Emitting YAML Performance

The otyher concern is the amount of time it take to write out a YAML files. The above code generates only a 570KB file but it take just under 8 seconds to write that file. Is this normal perfomance?

While most of my files are probably going to be much smaller than as while I plan to have many MBs would of data, I plan to have that data spread out over a lot of very small files instead of few but much larger files however 570KB file size does not seem out od the question and it taking almost 8 seconds seems a bit slow.

For reference, this is the code for `YamlUtility::saveAsFile()`

```cpp
#include <fstream>

#include "YamlUtility.hpp"

void YamlUtility::saveAsFile(YAML::Node node, std::string filePath) {
  std::ofstream myfile;

  myfile.open(filePath);
  myfile << node << std::endl;

  myfile.close();
}
```

**Comment by jbeder** [comment]
Thanks for following up.

**Comment by CairoLee** [comment]
Have the same problem, do we have any way to make it faster in debug mode?
that is really affect debugging efficiency..
