### ISSUE TITLE
Can yaml-cpp 6.0 compiled on the PowerPC version of OSX 10.4 (Tiger)?

### ISSUE THREAD

**Issue by TCH68k** [jbeder/yaml-cpp#610]
If yes, then which compiler (and which version) should be used for it?

**Comment by jbeder** [comment]
Probably, but I have no idea. Try it and see?

**Comment by TCH68k** [comment]
Okay, but which compiler i should use? What is the minimum version of gcc or clang to compile yaml-cpp? I know that gcc 4.8.1 was the first fully C++11 compatible gcc and the same is true for clang 3.3, but do i need all of the C++11 features?

**Comment by jbeder** [comment]
Probably you need a C++11-complete compiler.
