### ISSUE TITLE
Broken build process when using yaml-cpp as git submodule

### ISSUE THREAD

**Issue by rkrhlikar** [jbeder/yaml-cpp#612]
After the latest commit (https://github.com/jbeder/yaml-cpp/commit/3e33bb316651981916d623488caf2f8ee1b79b50) the CMake build process is broken if yaml-cpp is used as a git submodule. Running the cmake on the parent project results in the following error:
>CMake Error at /usr/local/share/cmake-3.11/Modules/ExternalProject.cmake:2525 (message):
>  No download info given for 'googletest_project' and its source directory:
>
>   \*\*PARENT_PROJECT_DIR\*\*/test/gtest-1.8.0
>
>  is not an existing non-empty directory.  Please specify one of:
>
>   * SOURCE_DIR with an existing non-empty directory
>   * DOWNLOAD_COMMAND
>   * URL
>   * GIT_REPOSITORY
>   * SVN_REPOSITORY
>   * HG_REPOSITORY
>   * CVS_REPOSITORY and CVS_MODULE
>Call Stack (most recent call first):
>  /usr/local/share/cmake-3.11/Modules/ExternalProject.cmake:3100 (_ep_add_download_command)
>  yaml-cpp/test/CMakeLists.txt:10 (ExternalProject_Add)

It seems that the `ExternalProject_Add()` command for googletest uses `${CMAKE_SOURCE_DIR}` as the `SOURCE_DIR` which results in the error above as it tries to drop the source files under the parent projects source directory.

The error is not present if test building is turned off.

**Comment by jbeder** [comment]
Thanks, rolled back (c90c08ccc9a08abcca609064fb9a856dfdbbb7b4).

**Comment by winterheart** [comment]
@rkrhlikar could you please provide your project for testing?

**Comment by rkrhlikar** [comment]
@winterheart I can't post the whole project as it is rather large, so I prepared a small example which has everything needed to reproduce the problem: https://github.com/rkrhlikar/yaml-cpp-issue-612-example

I only tested it on a system running Ubuntu 16.04 64-bit, but I think that it should work on other systems as well.

If you have any further questions/requests feel free to contact me.

**Comment by winterheart** [comment]
OK, thank you.
Created pr #613 for that.
