### ISSUE TITLE
undefined reference to `YAML::detail::node_data::empty_scalar[abi:cxx11]`

### ISSUE THREAD

**Issue by atar-axis** [jbeder/yaml-cpp#645]
Hey there!
First of all: Thank you very much for sharing this project and all your hard work!

Unfortunately I have a bad issue when using the lib on my Raspberry Pi
```
/tmp/ccwv1YlU.o: In function `YAML::Node::Scalar[abi:cxx11]() const':
main.cpp:(.text._ZNK4YAML4Node6ScalarB5cxx11Ev[_ZNK4YAML4Node6ScalarB5cxx11Ev]+0xa0): undefined reference to `YAML::detail::node_data::empty_scalar[abi:cxx11]'
collect2: error: ld returned 1 exit status
Makefile:17: recipe for target 'local' failed
make: *** [local] Error 1
```
I compiled the library using cmake and make, after that I linked it to an application and got the error above.

While trying to find out the cause i discovered #640, the problem is: I have not installed any other yaml-cpp library!

By the way, I am getting the same error when compiling the application using a cross compiler on my local machine: `arm-linux-gnueabihf-g++`, I am linking then to the `libyaml-cpp.a` which was compiled on the raspberry pi). Is there a way to cross-compile the library?

**Comment by atar-axis** [comment]
strange... the libs (one compiled on the raspberry pi, the other on my local machine) differ a lot!

library compiled on raspberry-pi (arm):
```
flood@flood-r3:[arm]$ nm libyaml-cpp.a --demangle | grep empty_scalar
         U YAML::detail::node_data::empty_scalar[abi:cxx11]()
00000000 b guard variable for YAML::detail::node_data::empty_scalar[abi:cxx11]()::svalue
00000000 T YAML::detail::node_data::empty_scalar[abi:cxx11]()
00000004 b YAML::detail::node_data::empty_scalar[abi:cxx11]()::svalue
```

library compiled on my local machine:
```
flood@flood-r3:[local]$ nm libyaml-cpp.a --demangle | grep empty_scalar
                 U YAML::detail::node_data::empty_scalar[abi:cxx11]
0000000000000000 t _GLOBAL__sub_I__ZN4YAML6detail9node_data12empty_scalarB5cxx11E
0000000000000000 B YAML::detail::node_data::empty_scalar[abi:cxx11]
```

**Comment by atar-axis** [comment]
btw, the same error occurs when you compile the library with `arm-linux-gnueabihf-g++` and when you link it afterwards using the same compiler/linker.

**Comment by atar-axis** [comment]
to reproduce this issue:

main.cpp
```
#include "yaml-cpp/yaml.h"
using namespace std;


YAML::Node config = YAML::LoadFile("config.yaml");

int main(int argc, char** argv)
{
	config["qr"].as<int>();
	return 0;
}
```

command to compile main.cpp:
```arm-linux-gnueabihf-g++ main.cpp -Iinc -Llib/arm  -lyaml-cpp -Wall -o bin/arm/loader```

content of toolchain.cmake to build the library using the cross compiler:
```
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc)
SET(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++)
SET(CMAKE_ASM_COMPILER arm-linux-gnueabihf-gcc)
SET(CMAKE_SYSTEM_PROCESSOR arm)

#ADD_DEFINITIONS("-march=armv6")
add_definitions("-mcpu=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard -marm")

# rdynamic means the backtrace should work
IF (CMAKE_BUILD_TYPE MATCHES "Debug")
   add_definitions(-rdynamic)
ENDIF()

# avoids annoying and pointless warnings from gcc
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -U_FORTIFY_SOURCE")
SET(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} -c")
```

build the lib using:
```cmake -DCMAKE_TOOLCHAIN_FILE=./toolchain.cmake ..```

**Comment by atar-axis** [comment]
```
nm --extern-only --defined-only -C local/libyaml-cpp.a | grep -i empty_scalar
0000000000000000 B YAML::detail::node_data::empty_scalar[abi:cxx11]
```
**vs.**
```
nm --extern-only --defined-only -C arm/libyaml-cpp.a | grep -i empty_scalar
00000000 T YAML::detail::node_data::empty_scalar[abi:cxx11]()
```

**Comment by atar-axis** [comment]
okay, I finally found the problem: my headers where outdated... they didn't match the lib.

**Comment by ZhixiongSun** [comment]
hey @atar-axis, I also had the same issue, could you please tell me which headers you used to solve this problem?

**Comment by Lanceart** [comment]
> hey @atar-axis, I also had the same issue, could you please tell me which headers you used to solve this problem?

I also met the same problem at first. I think he means you should include the right directories in your cmake config file.

**Comment by Phoenix8215** [comment]
Maybe you should include you *.h file which are in different directories recursively.🚀🚀🚀
```CMakeLists
function(include_sub_directories_recursively root_dir)
    if (IS_DIRECTORY ${root_dir})               # 当前路径是一个目录吗，是的话就加入到包含目录
        message("include dir: " ${root_dir})
        include_directories(${root_dir})
    endif()

    file(GLOB ALL_SUB RELATIVE ${root_dir} ${root_dir}/*) # 获得当前目录下的所有文件，让如ALL_SUB列表中
    foreach(sub ${ALL_SUB})
        if (IS_DIRECTORY ${root_dir}/${sub})
            include_sub_directories_recursively(${root_dir}/${sub}) # 对子目录递归调用，包含
        endif()
    endforeach()
endfunction()

include_sub_directories_recursively(${CMAKE_SOURCE_DIR}/include) 
```
