### ISSUE TITLE
Typo in Wiki

### ISSUE THREAD

**Issue by MarkOates** [jbeder/yaml-cpp#652]
Under the [Optional Keys](https://github.com/jbeder/yaml-cpp/wiki/How-To-Parse-A-Document-(Old-API)#optional-keys) section here:

> If you try to access a key that doesn't exist, yaml-cpp throws an exception (see When Something Goes Wrong. If you have optional keys, **you it's often easier** to use FindValue instead of operator[]:

**Comment by jbeder** [comment]
Fixed, thanks.

**Comment by MarkOates** [comment]
Thank _you_ for the lib 🙏.  Huge gains thanks to this project.
