### ISSUE TITLE
wrong boolean conversion on dcitionary-type key

### ISSUE THREAD

**Issue by razcore-art** [jbeder/yaml-cpp#663]
Hello there, this project is used by [this godot plugin](https://github.com/Beliaar/godot-yaml) and I discovered this issue. So the plugin creator made a YAML parser for Godot data types which among other things include `Array`, `Dictionary` and other stuff. While using it I saw that something like:

```yaml
pos:
  x: 0
  y: 0
y: n
```

which should produce this dictionary: `{"pos": {"x": 0, "y": 0}, "y": "n"}` instead returns `{"pos": {"x": 0, true: 0}, true: false}` which means there's an implicit conversion to boolean types if `y`/`n` is encountered, possibly some other values too, like `yes`/`no` etc.

For a parser project like that one this implicit conversion isn't desirable. Is there a way to force the strings on all values other than `true`/`false`? i.e.

```yaml
pos:
  x: true
  y: false
```

only `true`/`false` should be treated as real booleans.

**Comment by sanssecours** [comment]
I do not think yaml-cpp is causing the problems you mentioned above. At least a [plugin I wrote](https://www.libelektra.org/plugins/yamlcpp) that uses yaml-cpp `0.6` does not show this behavior.

**Comment by jbeder** [comment]
I think @sanssecours is right - can you give a small code example that exhibits the behavior you're describing?

**Comment by razcore-art** [comment]
So, I'm not sure how this works, my C++ is rusty, but looking at the code it seems that `::YAML::Node.as()` works with a custom function we define in the `YAML` namespace, called `decode` or something like that. And this `decode` function uses `decode_dictionary(const Node &node)` at the base cause in Godot the top level is a `Dictionary` type.

I didn't see anything weird, but then again, I'm not too sure what I'm looking at :).

The call takes place here: https://github.com/Beliaar/godot-yaml/blob/0cb6acaf4ca0652bd5de25120b56ccee50d7d560/src/godotconversions.cpp#L470 and the definition is here: https://github.com/Beliaar/godot-yaml/blob/0cb6acaf4ca0652bd5de25120b56ccee50d7d560/src/godotconversions.cpp#L181.

I can't give any C++ code that works with this because this is compiled to a library to be used by Godot in it's own scripting language: GDScript. To be honest I'm not even sure how I'd use this library in C++, but maybe you can spot something.

Thanks a lot!

**Comment by jbeder** [comment]
Interesting! It looks like [here](https://github.com/Beliaar/godot-yaml/blob/0cb6acaf4ca0652bd5de25120b56ccee50d7d560/src/godotconversions.cpp#L487) the code checks if the thing can be cast to a boolean, and that call happens before the "fallback", where it just reads it as a string.

So what's happening isn't that yaml-cpp is insisting `y` is a boolean and *not* a string; rather, it's allowed to be either, depending on what the code asks, and this code happens to ask for a boolean first.

**Comment by razcore-art** [comment]
Ah! I looked at that but didn't make the connection with the fallback process. Thanks a bunch!

**Comment by Stef-Sijben** [comment]
As noted before, only `true` and `false`, including upper-case variations are considered bools in the YAML 1.2 spec, see [the changelog](https://yaml.org/spec/1.2.2/ext/changes/) for YAML 1.2.

However, in [YAML 1.1](https://yaml.org/type/bool.html), `yes`,`no`,`on`,`off` and a number of variations were also defined as Boolean values.

[It appears that yaml-cpp is following the YAML 1.1 convention](https://github.com/jbeder/yaml-cpp/blob/0d9dbcfe8c0df699aed8ae050dddaca614178fb1/src/convert.cpp#L50). Since yaml-cpp claims to follow the YAML 1.2 spec, the current behaviour is incorrect.
