### ISSUE TITLE
Is it dead yet

### ISSUE THREAD

**Issue by Zingam** [jbeder/yaml-cpp#673]
The library feels great but it has issues with VS2019 and C++17, and maybe it will be even worse with C++20. I don't see much development happening here. Is this library still alive and reliable?

**Comment by jbeder** [comment]
It's in patches-welcome state. I try to review PRs, and I don't have a windows box so I can't test anything there. Unfortunately I couldn't figure out how to set up any automated windows testing, but I'd love if someone contributed that. (There was someone that seemed interested in that, but then disappeared.)

**Comment by Zingam** [comment]
> It's in patches-welcome state. I try to review PRs, and I don't have a windows box so I can't test anything there. Unfortunately I couldn't figure out how to set up any automated windows testing, but I'd love if someone contributed that. (There was someone that seemed interested in that, but then disappeared.)

What is "run-test" from .travis.yml:
```
script:
  - make
  - test/run-tests
```

**Comment by jbeder** [comment]
That’s the testing binary.

**Comment by Zingam** [comment]
@jbeder I figured it out. I made a pull request. If that goes well next I'll do the dll issues. I've fixed them but I'll need to redo them against the HEAD.
