### ISSUE TITLE
Node will crash if the key of the node is missing

### ISSUE THREAD

**Issue by HensonLi** [jbeder/yaml-cpp#679]

**Comment by HensonLi** [comment]
eg:
com.hh.example:
    permission: 1,2
    bookManager:
        : com.hh.example.BookManagerService
        addBook:
        getFrontBook:
            methodNumber: 1
            permission: 1

**Comment by jbeder** [comment]
Could you provide a minimal code example as well? (And please format the YAML example so it's possible to see indentation.)

**Comment by HensonLi** [comment]
sample code:
    `const YAML::Node packageNode = rNode[packageName];`
    `for (const auto &sNode : packageNode) {`
        `std::string packageProperty = sNode.first.as<std::string>();`
    `}`
withe the code upper, parse the yaml file shown in the attachment (.png picture), pay attention the third line in the .png file, when the key is missing, the line `std::string packageProperty = sNode.first.as<std::string>();` in the sample code will crash, and output error log as "YAML::TypedBadConversion", i think we should add a method to check if the node is invalid(not `IsNull`, but to check if all the component of the node are allright).

![2019-03-01 10-17-38](https://user-images.githubusercontent.com/30543322/53611978-5cc17580-3c0b-11e9-8903-ae85261ffc1d.png)

**Comment by jbeder** [comment]
This is WAI. The node is not a string, it's null, so you can't interpret it as a string.

(By the way, this isn't a crash, but rather an exception being thrown and not caught. The word "crash" is usually used to describe something like a segfault.)
