### ISSUE TITLE
yaml-cpp now available in conda-forge

### ISSUE THREAD

**Issue by allanleal** [jbeder/yaml-cpp#680]
Hello. Just want to tell you and the contributors of this project that `yaml-cpp` is now available in the [conda-forge repository](https://anaconda.org/conda-forge/yaml-cpp). This enables its installation using conda:

~~~
conda install -c conda-forge yaml-cpp 
~~~

You may want to update the installation instructions to address this new install mode.

**Comment by MrScriptMaster** [comment]
Ваш отчет успешно принят и ожидает проверки.

**Comment by jbeder** [comment]
Thanks! I usually don't document the different packages that include it, but I appreciate the work!

**Comment by allanleal** [comment]
Well, too bad. This would be highly appreciated by users of yaml-cpp that rely on conda for package dependency manager.

See the [docs](https://github.com/nlohmann/json#package-managers) of `nlohmann::json` lib for example:

> If you are using conda, you can use the package nlohmann_json from conda-forge executing conda install -c conda-forge nlohmann_json.
