### ISSUE TITLE
What license exactly is yaml-cpp opensourced under?

### ISSUE THREAD

**Issue by 130s** [jbeder/yaml-cpp#684]
http://changelogs.ubuntu.com/changelogs/pool/universe/y/yaml-cpp/yaml-cpp_0.6.2-4fakesync1/copyright shows `X11` and `GPL` while https://github.com/jbeder/yaml-cpp/blob/master/LICENSE shows MIT on github. What is correct?

**Comment by jbeder** [comment]
GitHub is correct, as long as it’s the same code. I haven’t checked your
other link.

**Comment by 130s** [comment]
Thanks for prompt response.

"Other link" is the `copyright` file that gets installed on debian/Ubuntu. I believe there are non-trivial number of people who see this file to check the package license. On my Ubuntu it shows `GPL`.

```
# tail /usr/share/doc/libyaml-cpp-dev/copyright 
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 .
 You should have received a copy of the GNU General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>
 .
 On Debian systems, the complete text of the GNU General
 Public License version 2 can be found in "/usr/share/common-licenses/GPL-2".

# apt-cache policy libyaml-cpp-dev
libyaml-cpp-dev:
  Installed: 0.5.2-4ubuntu1~16.04.4
  Candidate: 0.5.2-4ubuntu1~16.04.4
```

**Comment by KitsuneRal** [comment]
Linux packagers are not always doing a good job at tracking licenses, especially outside of basic set of packages. Ubuntu Universe is one prominent example of that. You should reach out to the maintainer who's made that package, rather than upstream.
