### ISSUE TITLE
new release after 0.6.2

### ISSUE THREAD

**Issue by david-antiteum** [jbeder/yaml-cpp#700]
The last release is from more that one year ago. It is possible to do a new one? I need it to update [vcpkg port](https://github.com/Microsoft/vcpkg/blob/master/ports/yaml-cpp/CONTROL) (and to suppress some warnings as STL4015 that have been already addressed).

Thanks.

**Comment by noizex** [comment]
Yeah, I'd also like to have new version for Hunter package - current one (0.6.2) has an error which doesn't allow modern MSVC to compile the project due to too hardcoded _MSC_VER condition. When can we expect the next version release, please?

**Comment by webbnh** [comment]
Me, too!  :-)  We would like a "released" version which doesn't hit the #600 warning.

**Comment by StableCoder** [comment]
I would concur. Attempting to build on MSVC 19.20 (2019) also breaks due to the hardcoded _MSC_VER fixed with PR https://github.com/jbeder/yaml-cpp/pull/597.

Are there any particular items that need to be addressed before a new release? If so, detailing them might help get things moving.

**Comment by tomkirkhawkeye** [comment]
@jbeder Any update on when a next release is likely?

**Comment by ScarletKuro** [comment]
waiting for new release too

**Comment by WilliamTambellini** [comment]
I also call for a new version tag : 0.6.2 is already 1 year old, from mid 2018.
What about at least a new 0.6.3 git tag ?

**Comment by Samonitari** [comment]
A new release containing #300 and #741 could be awesome, please!

**Comment by WilliamTambellini** [comment]
@jbeder  Are you still alive and/or working on this project ?

**Comment by jbeder** [comment]
Done:

https://github.com/jbeder/yaml-cpp/releases/tag/yaml-cpp-0.6.3
