### ISSUE TITLE
double free or corruption error

### ISSUE THREAD

**Issue by lsrock1** [jbeder/yaml-cpp#703]
when i run this code
`YAML::Node default_config;  
  YAML::Node model;
  model["RPN_ONLY"] = false;`

I got some pointer error
double free or corruption (out): 0x00007fff465b42e0

Is there anything that i missed?

in ubuntu 18

**Comment by jbeder** [comment]
What is telling you this error? Can you post a complete working example?

**Comment by lsrock1** [comment]
in project's root CMakelists.txt

`find_package(yaml-cpp REQUIRED)  
target_link_libraries(${OUTPUT}  yaml-cpp)`

and in cpp file
`#include "defaults.h"
#include "yaml-cpp/yaml.h"

namespace rcnn{
namespace config{

YAML::Node GetDefaultCFG(){
  YAML::Node default_config = YAML::LoadFile("/root/e2e_faster_rcnn_R_50_FPN_1x.yaml");  
  YAML::Node model;  
  model["RPN_ONLY"] = false;
}
}
}`

It fails in model["RPN_ONLY"]
ERROR SHOWS
double free or corruption (out): 0x00007fffd0aaa8b0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7facf26467e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7facf264f37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7facf265353c]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSsD2Ev+0x64)[0x7facf2c7e0b4]
./rcnncpp-0.1.out(_ZN4YAML4NodeD1Ev+0x2c)[0x405b26]
/root/maskrcnn/build/source/rcnn/config/libconfig.so(_ZN4YAML6detail9node_data15convert_to_nodeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERNS0_4nodeERKT_St10shared_ptrINS0_13memory_holderEE+0x79)[0x7facfd4af2d5]
/root/maskrcnn/build/source/rcnn/config/libconfig.so(_ZN4YAML6detail9node_data3getINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERNS0_4nodeERKT_St10shared_ptrINS0_13memory_holderEE+0x201)[0x7facfd4ae437]
/root/maskrcnn/build/source/rcnn/config/libconfig.so(_ZN4YAML6detail8node_ref3getINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERNS0_4nodeERKT_St10shared_ptrINS0_13memory_holderEE+0x59)[0x7facfd4ac815]
/root/maskrcnn/build/source/rcnn/config/libconfig.so(_ZN4YAML6detail4node3getINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERS1_RKT_St10shared_ptrINS0_13memory_holderEE+0x59)[0x7facfd4aab2f]
/root/maskrcnn/build/source/rcnn/config/libconfig.so(_ZN4YAML4NodeixIA9_cEES0_RKT_+0xe0)[0x7facfd4a6942]
/root/maskrcnn/build/source/rcnn/config/libconfig.so(_ZN4rcnn6config13GetDefaultCFGEv+0x141)[0x7facfd4a04d9]
./rcnncpp-0.1.out(main+0x23)[0x404dce]
[0xe10fe0]
