### ISSUE TITLE
YAML::Load exception for simple case

### ISSUE THREAD

**Issue by gxhblues** [jbeder/yaml-cpp#705]
I'm not 100% sure if my compile flags are correct, but YAML::Load works for many complex cases, except some simple cases. e.g.
```
A: 123
B: "123"
```
Load this string with YAML::Load, I get an exception: 

> yaml-cpp: error at line 2, column 11: unknown escape character:

**Comment by gxhblues** [comment]
And, if put something at the end of string, it works. e.g.
```
A: 123
B: "123"
#
```

**Comment by dota17** [comment]
I can parse your example with YAML::Load successfully.  It may be that your usage is wrong or the problem has been fixed.

**Comment by jbeder** [comment]
Thanks, @dota17. I'm marking this closed, and @gxhblues, if you still believe this is a bug, please post your code along with the YAML so we can try to reproduce it.
