### ISSUE TITLE
yaml-cpp fails to parse YAML it emits

### ISSUE THREAD

**Issue by till-s** [jbeder/yaml-cpp#707]
YAML::Emitter emits map entries ( key: value ) when the key is actually an alias (`*keyalias`) as

    *keyalias: value

(note that there is no space between the alias name and ':'). However, the parser exceptions out when being fed what YAML::Emitter produces. The parser accepts 

    *keyalias : value

though (note space between alias and ':').

Unfortunately, the YAML 1.2 spec is too complex for me to quickly grasp if there is a violation and what it would be. It seems to me that the colon could be a legal part of an alias name which would imply that the emitter is to blame.

A very simple test program is attached.

Obviously, normal plain-string keys (i.e., not aliases) work fine

    key: value

[bug.cc.txt](https://github.com/jbeder/yaml-cpp/files/3193756/bug.cc.txt)

**Comment by till-s** [comment]
The bug is in the emitter. The YAML spec says

> `[102]  ns-anchor-char ::= ns-char - c-flow-indicator`
> `[103] | ns-anchor-name ::= ns-anchor-char+`

which means that `:` is a legal character of an anchor name. Thus, between the alias and `:` a blank would be required. It was not obvious to me how to do this from `Emitter::..MapPrepare..KeyValue()`, i.e., it is not clear how to know that the preceding key was an alias (or vice versa, when emitting an alias it is not clear how to know that a `:` will follow...).

The good news are that a work-around is available: emit keys in the 'long-key' format.

[bug-workaround.cc.txt](https://github.com/jbeder/yaml-cpp/files/3679016/bug-workaround.cc.txt) illustrates how to do this.

**Comment by till-s** [comment]
Unfortunately the work-around above is not helpful due to [another bug](https://github.com/jbeder/yaml-cpp/issues/752) which kicks in when anchored map values are emitted in long-key format :-(

**Comment by dota17** [comment]
Fixed by #929
