### ISSUE TITLE
Can't remove from a sequence

### ISSUE THREAD

**Issue by xavi-b** [jbeder/yaml-cpp#708]
I have seen commit [4fb1c4b92bf8d94b32ebccdd890407d45b3bc794](https://github.com/jbeder/yaml-cpp/commit/4fb1c4b92bf8d94b32ebccdd890407d45b3bc794).

But despite my node being a sequence, calling node.remove(0) returns false.

**Comment by xavi-b** [comment]
Test code:
```
#include <iostream>
#include <yaml-cpp/yaml.h>

int main(int argc, char* argv[])
{
    YAML::Node node = YAML::Load("[{name: test, children: []}]");
    std::cout << node << std::endl;
    std::cout << node.remove(0) << std::endl;
    return 0;
}
```
Returns:
```
[{name: test, children: []}]
0
```

**Comment by tt4g** [comment]
Are you using the `master` branch source?

The last released version 0.6.2 should not contain any changes due to the commit.

**Comment by xavi-b** [comment]
I'm on archlinux using yaml-cpp 0.6.2-1

**Comment by tt4g** [comment]
As far as I see the archlinux yaml-cpp, it looks like a version 0.6.2 distributed on the GitHub release page.

https://www.archlinux.org/packages/community/x86_64/yaml-cpp/

The yaml-cpp you are using will not contain the change of commit ID 4fb1c4b92bf8d94b32ebccdd890407d45b3bc794.

**Comment by xavi-b** [comment]
Oh my mistake ! I read the wrong year.
