### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by gvjosyer** [jbeder/yaml-cpp#709]
Hi,

I would like to get a list of known issues for a particular version of yaml-cpp. Please let me know how this can be extracted

Thanks and Regards,
Venkatesh

**Comment by jbeder** [comment]
Under the "Issues" tab in github.

**Comment by gvjosyer** [comment]
Thanks for your response.

I did use the filter 'label:Milestone-Release0.3.0' which resulted in 4 issues. Can you confirm if these 4 issues were reported in Release 0.3.0 and fixed in a later release?

**Comment by jbeder** [comment]
It looks like those 4 issues are closed. So yes, they have been fixed.
