### ISSUE TITLE
the undefined types "YAML::convert<T>" and "encode": The identifier was not found

### ISSUE THREAD

**Issue by lvpinrui** [jbeder/yaml-cpp#720]
hello, I created new project  reference to the generated  release library
When building the new project, the file /node/impl.h appears using the undefined types "YAML::convert<T>" and "encode": The identifier was not found
![image](https://user-images.githubusercontent.com/44189445/62608497-7d1bfb80-b932-11e9-8e45-6fb5587befe2.png)
waiting for your reply,thank you!

**Comment by lvpinrui** [comment]
I  created the project in windows vs2015

**Comment by WLwind** [comment]
Hello. Have you solved this problem? A simlar problem comes to me too.
