### ISSUE TITLE
Bazel Support

### ISSUE THREAD

**Issue by zaucy** [jbeder/yaml-cpp#722]
I would love to see support for [Bazel](https://bazel.build/) in this repository. Would this be something that interests the maintainers here?

I made a fork with the necessary bazel build files over [here](https://github.com/bazelregistry/yaml-cpp), but it would be great to have support from the official repository. I'd be willing to help with improvements or any issues that come up in relation to bazel.

**Comment by jbeder** [comment]
Yep, I'd be happy to put a Bazel file in yaml-cpp! PR welcome :)
