### ISSUE TITLE
YAML_CPP_INCLUDE_DIR variable not set correctly in CMake

### ISSUE THREAD

**Issue by muzammil360** [jbeder/yaml-cpp#725]
`YAML_CPP_INCLUDE_DIR` variable is not set correctly in CMake.

Value return by this variables: `/usr/local/include/`
Actual header file installation: `/usr/local/include/yaml-cpp`

Kindly, fix this. I built the library at: `012269756149ae99745b6dafefd415843d7420bb`

**Comment by sanssecours** [comment]
I think you are supposed to include the library like this:

```cpp
#include "yaml-cpp/yaml.h"
```

. For that approach, `YAML_CPP_INCLUDE_DIR` is set correctly, as far as I can tell.

**Comment by muzammil360** [comment]
@sanssecours, yes, I agree. Thanks for the quick help.
