### ISSUE TITLE
CMake broken: "target pattern contains no `%'"

### ISSUE THREAD

**Issue by asmaloney** [jbeder/yaml-cpp#745]
The recent [major changes to CMake](https://github.com/jbeder/yaml-cpp/pull/741) broke my build when using yaml-cpp as a submodule. I removed my shadow build directory and ran CMake from scratch.

No errors when running CMake, but when building I get this:

> extern/yaml-cpp/CMakeFiles/yaml-cpp.dir/build.make:458: *** target pattern contains no `%'.  Stop.

The line it's pointing at is this:

> extern/yaml-cpp/libyaml-cpp$<$<AND:$<NOT:$<BOOL:OFF>>,$<CONFIG:Debug>>:d>.a: extern/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/binary.cpp.o

Are there changes I need to make to my own cmake files to use it now?

macOS 10.14.6
Apple clang version 11.0.0 (clang-1100.0.33.8)
cmake version 3.15.3
CMAKE_BUILD_TYPE: debug

**Comment by jbeder** [comment]
No idea. I commented on that change to see if slurps-mad-rips knows

**Comment by asmaloney** [comment]
Looks like it might have to do with escaping? 

https://stackoverflow.com/questions/15113138/target-pattern-contains-no-makefile

**Comment by asmaloney** [comment]
Here's more context from the Makefile command:

```
extern/yaml-cpp/libyaml-cpp$<$<AND:$<NOT:$<BOOL:OFF>>,$<CONFIG:Debug>>:d>.a: extern/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/binary.cpp.o
extern/yaml-cpp/libyaml-cpp$<$<AND:$<NOT:$<BOOL:OFF>>,$<CONFIG:Debug>>:d>.a: extern/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/convert.cpp.o
[...snip...]
extern/yaml-cpp/libyaml-cpp$<$<AND:$<NOT:$<BOOL:OFF>>,$<CONFIG:Debug>>:d>.a: extern/yaml-cpp/CMakeFiles/yaml-cpp.dir/build.make
extern/yaml-cpp/libyaml-cpp$<$<AND:$<NOT:$<BOOL:OFF>>,$<CONFIG:Debug>>:d>.a: extern/yaml-cpp/CMakeFiles/yaml-cpp.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=build-foo-clang_64bit-Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_29) "Linking CXX static library \"libyaml-cpp\\\$$\$$<\\\$$\$$<AND:\\\$$\$$<NOT:\\\$$\$$<BOOL:OFF>>,\\\$$\$$<CONFIG:Debug>>:d>.a\""
	cd build-foo-clang_64bit-Debug/extern/yaml-cpp && $(CMAKE_COMMAND) -P CMakeFiles/yaml-cpp.dir/cmake_clean_target.cmake
	cd build-foo-clang_64bit-Debug/extern/yaml-cpp && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/yaml-cpp.dir/link.txt --verbose=$(VERBOSE)
```

Could have something to do with all that crazy escaping - `\\\$$\$$` :-)

**Comment by slurps-mad-rips** [comment]
Investigating. Just to check: does this happen if you use Ninja instead of Make?

**Comment by slurps-mad-rips** [comment]
Turns out it doesn't actually matter. The `DEBUG_POSTFIX` is only applied if `CMAKE_BUILD_TYPE` is Debug, so no generator expression is actually needed in this instance. Submitted a small PR to fix this. Apologies for the inconvenience. Ninja handles this correctly, but it seems the Makefile generator doesn't :(

**Comment by asmaloney** [comment]
No inconvenience at all - thanks for the CMake modernization! I learned some stuff which makes it a good day.

That PR fixes it for me.

**Comment by jbeder** [comment]
Thanks, both of you!
