### ISSUE TITLE
Don't break ABI with patch versions

### ISSUE THREAD

**Issue by svenstaro** [jbeder/yaml-cpp#747]
I just bumped 0.6.2 to 0.6.3 in Arch Linux and we received failures such as these:

`undefined symbol: _ZN4YAML6detail9node_data12empty_scalarB5cxx11E`

this is unexpected for patch version increases as those shouldn't break ABI.

Please increase minor version next time instead.

**Comment by jbeder** [comment]
Ack, my bad. Will do next time.
