### ISSUE TITLE
BUILD_SHARED_LIBS documentation no longer correct

### ISSUE THREAD

**Issue by sei-mwd** [jbeder/yaml-cpp#748]
Commit 5e9cb0128d1b600ff74505429269fd4dff367f4a causes shared libraries not to be built unless both BUILD_SHARED_LIBS and YAML_BUILD_SHARED_LIBS are set.  This is surprising to me, and the current documentation only mentions the latter variable.

**Comment by slurps-mad-rips** [comment]
@sei-mwd Apologies, this is a mistake on my part. Apologies. Are you trying to build the project as part of a large project structure, or by itself? I was trying to mimic the older behavior, while ensuring that CMake's "best practices" are followed. In this case, that means using the builtin `BUILD_SHARED_LIBS` variable. By default `YAML_BUILD_SHARED_LIBS` was turned off by default. I kept it this way in case someone wanted to enable `BUILD_SHARED_LIBS`, but didn't want to build all projects as such.  

@jbeder What's your opinion on having `YAML_BUILD_SHARED_LIBS` be enabled if `yaml-cpp` has both `BUILD_SHARED_LIBS` enabled *and* is the root project? Alternatively, we could take a different approach and provide a `yaml-cpp-static` and `yaml-cpp-shared` target, which is then aliased to the correct name based on these settings. CMake is set up that if a target is marked `EXCLUDE_FROM_ALL`, it won't build it unless used. This approach would probably solve @sei-mwd's issue, and future proof the project regarding "do I build this shared or static", and instead shifts the question to "Will I link against static or shared?"

**Comment by jbeder** [comment]
I'm not sure if I have an opinion here. It seems like this is not an
unusual situation we're in (it's an ordinary library that you might want to
build as static or shared), so I just want to do whatever's the standard
practice.

**Comment by sei-mwd** [comment]
My recommendation is that YAML_BUILD_SHARED_LIBS is the variable that makes the decision, and it's default value is the value of BUILD_SHARED_LIBS.  Someone who is including yaml-cpp as as a sub-project of something being built with shared libraries can can set YAML_BUILD_SHARED_LIBS to false, overriding the global default.

**Comment by sei-mwd** [comment]
Oh, and to actually reply to your initial question, I am building yaml-cpp as a library.  I'm using it as part of a larger build, yes, but that larger build is not intended to come with yaml-cpp built in.  Rather, it is intended that it use the system-provided package.  In this case, though, I am building images on a test server where I am personally curating all the dependencies, which includes yaml-cpp.

**Comment by slurps-mad-rips** [comment]
I'll be handling this later tonight/this weekend. Sorry for the delay. Work week gets in the way :)

**Comment by jbeder** [comment]
Thanks, and no worries, same here :)

**Comment by slurps-mad-rips** [comment]
Sorry for the long wait! Had a hell of a week 😅

**Comment by vfazio** [comment]
Any chance of cutting a release with this patch in it? Builds in Buildroot which leverage  BUILD_SHARED_LIBS for cmake packages could use this patch :+1:

**Comment by Windrow14** [comment]
Excuse me.

`-YAML_BUILD_SHARED_LIBS=ON` in the README confused green hand cmake user like me.

Should it be `-DYAML_BUILD_SHARED_LIBS=ON`?

**Comment by jbeder** [comment]
Yep, thanks! Fixed in 974349d015aa5a6a8c01600e775af35cb9253140.
