### ISSUE TITLE
yaml-cpp Emitter generates bad long keys

### ISSUE THREAD

**Issue by till-s** [jbeder/yaml-cpp#752]
This map is parsed correctly

    map1: &map_anch
      key: value
    map2: *map_anch

but the parsed hierarchy is re-emitted (when using long-key format) as

    ? map1
    : &1 ? key
      : value
    ? map2
    : *1

which cannot be parsed again. The correct output would be (newline after the anchor &1)

    ? map1
    : &1
      ? key
      : value
    ? map2
    : *1

A simple program reproducing the bug (just remove the '.txt' extension): 
[bug-longkey.cc.txt](https://github.com/jbeder/yaml-cpp/files/3679111/bug-longkey.cc.txt)

**Comment by till-s** [comment]
See also [this issue](https://github.com/jbeder/yaml-cpp/issues/707)

**Comment by dota17** [comment]
Fixed by #879.
