### ISSUE TITLE
CMake build configuration minimum version

### ISSUE THREAD

**Issue by fyazici** [jbeder/yaml-cpp#757]
It appears that the main CMakeLists.txt file utilizes `add_library` with omitted sources. This feature is not supported in cmake 3.10.? and below. Noticed the issue while configuring on a machine with Ubuntu 16.04 cmake 3.10.2. I suggest that the minimum version statement be updated to at least 3.11 so that cmake fails in a more understable way.

**Comment by jbeder** [comment]
3.11 is too recent, I think (Feb 2018). Can you instead update it to work
on earlier CMakes? (I don't understand what "omitted sources" means.)

**Comment by fyazici** [comment]
I did not dig into the file any deeper than finding the culprit but I will look and see what I can do (though I am not very experienced in CMake) in about a day from now.

**Comment by ashpekvs** [comment]
3.10 cmake fails to build the lib on Ubuntu 18.04.3 x64 LTS
issues with pthreads lib (can't find it)

3.15.4 worked like a charm!
built 100%

**Comment by fyazici** [comment]
solved by #763
