### ISSUE TITLE
Build fails on CMAKE version 3.10.2 

### ISSUE THREAD

**Issue by azubieta** [jbeder/yaml-cpp#759]
When trying to build the latest commit from master I got the following cmake error:
```
CMake Error at test/CMakeLists.txt:23 (add_executable):
  add_executable called with incorrect number of arguments
```

Which points to this line: https://github.com/jbeder/yaml-cpp/blame/master/test/CMakeLists.txt#L23

**Comment by swartik** [comment]
Glad I'm not the only one to encounter this. According to the cmake documentation, add_executable requires at least one source in versions 3.0–3.10. Starting with version 3.11.4, sources are optional.

**Comment by fyazici** [comment]
should be solved by #763 
 can you ( @azubieta and @swartik ) please confirm?

**Comment by swartik** [comment]
It works now with cmake version 3.10. Thanks!

**Comment by azubieta** [comment]
Thanks !
