### ISSUE TITLE
using a std::string_view for YAML::Load() override

### ISSUE THREAD

**Issue by senior7515** [jbeder/yaml-cpp#765]
I'd like to propose and make a change to have an override that supports loading from a string_view rather than from a concrete type. 

https://github.com/jbeder/yaml-cpp/blob/4fb1c4b92bf8d94b32ebccdd890407d45b3bc794/include/yaml-cpp/node/parse.h#L24

Rationale:

I have my own string class and an async way from loading files from disk (libaio) backed. 

1. I don't want to block my reactor thread from loading up from disk using the load file
2. Producing a string_view is relatively easy and efficient for me
3. I don't want to copy my buffer into yet another conversion (std::string) so I can pass a reference into the method. 
4. there is no override for the `(const char*, size_t)` which doesn't allow me to manipulate what part of the buffer gets loaded, i think the default constructor `(const char*)` is basically assuming a null-terminated string which is not the case for me since after the size there are other bytes. 
5. `std::string_view` is part of the standard now and likely going to be the new interface for byte ranges from a string-looking buffer. 
6. Alternatively, we can just add a `(const char*, size_t)` overload (a poor's man string_view)

Thank you and let me know!

**Comment by senior7515** [comment]
7. there is an implicit converstion from a `const string &` -> `std::string_view` that will do the right thing, so everything gets wired up nicely.

**Comment by jbeder** [comment]
Yes, I believe that would be fine. I'll accept a PR>

**Comment by senior7515** [comment]
@jbeder I did some exploration, and it looks like we'd have to wrap in a stringstream since that's what the other methods do in  `parser.cpp`

Looking at the gcc implementation:

```
  // [string.view.io], Inserters and extractors
  template<typename _CharT, typename _Traits>
    inline basic_ostream<_CharT, _Traits>&
    operator<<(basic_ostream<_CharT, _Traits>& __os,
	       basic_string_view<_CharT,_Traits> __str)
    { return __ostream_insert(__os, __str.data(), __str.size()); }

```
it basically copies all the data (expected), so we'd probably have to write a wrapper for `std:istream`

```

// from the libc++v3 gcc impl

class istream : public ios
{
    size_t _gcount;
  public:
    istream();
    istream(streambuf* sb, ostream*tied=(__null) );
    ~istream();
    streambuf* istreambuf() const { return _strbuf; }
    istream& get(char& c);
    istream& get(unsigned char& c);
    istream& read(char *ptr, int n);
    istream& read(unsigned char *ptr, int n) { return read((char*)ptr, n); }
    istream& read(void *ptr, int n) { return read((char*)ptr, n); }
    int get() { return _strbuf->sbumpc(); }
    istream& getline(char* ptr, int len, char delim = '\n');
    istream& get(char* ptr, int len, char delim = '\n');
    istream& gets(char **s, char delim = '\n');
    int ipfx(int need) 
```

To make the effort of string_view worth it.

**Comment by jbeder** [comment]
Ah, that seems plausible. I had looked into doing some more efficient stream-like things (avoiding copies and so forth) a while ago, and got far down a rabbit hole and it looked like still a ton of work.

Still happy to accept a PR, but be wary that (1) it's probably a ton of work, (2) you'll have to make extra effort to make it readable, since this stuff can get messy quickly, and (3) you'll have to be careful we don't have buffer overruns, etc.

**Comment by senior7515** [comment]
100%.  I am going to close this for now. instead of paying 2 copies

1. to std::string
2. to string stream 

I am wrapping my custom type in a quick function which does just fine


```
template<typename Iterator>
inline std::stringstream to_stringstream(Iterator begin, Iterator end)
    std::stringstream ss;
    std::copy(begin, b, std::ostream_iterator<char>(ss));
    return ss;
}
```

Thanks!
