### ISSUE TITLE
Does not compile with Visual studio 2013 due to missing defaulted move constructor support

### ISSUE THREAD

**Issue by pvaddina** [jbeder/yaml-cpp#766]
Hi,
The code does not compile for VS 2013. I faced two issues:
1. CMake generates incorrect project label for the project yaml-cpp. As a result VS 2013 ends up in the error:

> error MSB3491: Could not write lines to file "yaml-cpp.dir\Debug\yaml-cpp.08AA9AF5.tlog\yaml-cpp $<IF:$<BOOL:OFF>,shared,static>.lastbuildstate". Illegal characters in path.

2. Using a work around, i was able to compile the project but with errors. VS 2013 compiler does not support defaulted move constructors and defaulted destructors. 

> C2264: 'YAML::StreamCharSource::StreamCharSource' : error in function definition or declaration; function not called	
> C2610: 'YAML::BadConversion::~BadConversion(void) throw()' : is not a special member function which can be defaulted	
> C2610: 'YAML::BadDereference::~BadDereference(void) throw()' : is not a special member function which can be defaulted	
> C2610: 'YAML::BadFile::~BadFile(void) throw()' : is not a special member function which can be defaulted	
> C2610: 'YAML::BadInsert::~BadInsert(void) throw()' : is not a special member function which can be defaulted	
> C2610: 'YAML::BadPushback::~BadPushback(void) throw()' : is not a special member function which can be defaulted	
> C2610: 'YAML::BadSubscript::~BadSubscript(void) throw()' : is not a special member function which can be defaulted	
> C2610: 'YAML::Binary &YAML::Binary::operator =(YAML::Binary &&)' : is not a special member function which can be defaulted	
> C2610: 'YAML::Binary::Binary(YAML::Binary &&)' : is not a special member function which can be defaulted	
> C2610: 'YAML::EmitterException::~EmitterException(void) throw()' : is not a special member function which can be defaulted	
> C2610: 'YAML::Exception::~Exception(void) throw()' : is not a special member function which can be defaulted	
> C2610: 'YAML::InvalidNode::~InvalidNode(void) throw()' : is not a special member function which can be defaulted	
> C2610: 'YAML::InvalidScalar::~InvalidScalar(void) throw()' : is not a special member function which can be defaulted	
> C2610: 'YAML::KeyNotFound::~KeyNotFound(void) throw()' : is not a special member function which can be defaulted	
> C2610: 'YAML::ParserException::~ParserException(void) throw()' : is not a special member function which can be defaulted	
> C2610: 'YAML::ptr_vector<T> &YAML::ptr_vector<T>::operator =(YAML::ptr_vector<T> &&)' : is not a special member function which can be defaulted	
> C2610: 'YAML::ptr_vector<T>::ptr_vector(YAML::ptr_vector<T> &&)' : is not a special member function which can be defaulted	
> C2610: 'YAML::RepresentationException::~RepresentationException(void) throw()' : is not a special member function which can be defaulted	
> C2610: 'YAML::SettingChanges::SettingChanges(YAML::SettingChanges &&)' : is not a special member function which can be defaulted	
> C2610: 'YAML::StreamCharSource::StreamCharSource(YAML::StreamCharSource &&)' : is not a special member function which can be defaulted	
> C2610: 'YAML::TypedKeyNotFound<T>::~TypedKeyNotFound(void) throw()' : is not a special member function which can be defaulted	
> C2797: 'YAML::Directives::version': list initialization inside member initializer list or non-static data member initializer is not implemented

I fixed both the issues by:
1. Not using a PROJECT_LABEL property for the yaml-cpp project in the CMakeLists.txt
2. By implementing the move constructors to do element wise move and providing a default empty implementation for the destructors

The question is: 
- Did any one notice the issue ? 
- Can I deliver these changes ?

Thank you
Prakash

**Comment by pvaddina** [comment]
Forgot to mention:
cmake version 3.9.1

BR,
Prakash

**Comment by jbeder** [comment]
Unfortunately, I haven't been able to figure out how to get continuous testing with MSVC, so Windows is a blind spot here.

For the project label: I don't really follow all the CMake stuff, so happy to accept a PR if it's reasonable (and doesn't break the other platforms).

For the default methods: I'm more hesitant; what's the earliest version of MSVC that handles these defaults right?

**Comment by pvaddina** [comment]
Regarding the CMAKE issue: The suggested fix only effects the project label and nothing else. So, this should have no effect on any other platforms. 

Regarding default methods: I can understand your hesitation. But theoretically changing the default move constructors to element wise move, the behavior should be exactly same as early. In the same way, for defaulted destructors, it is enough if they have an empty implementation. IMHO, this should not effect any other platforms. The only drawback being it is not so "modern" C++ anymore. I think the earliest version of MSVC which supports all (at least most) C++11 features is VS2015. However I do not have it installed on my PC.

**Comment by jbeder** [comment]
It's not just that it's not modern C++ any more; it's also more error-prone (what if you miss a field? what if a new field gets added and you forget to move it?).

I think the bottom line is: we require C++ 11. If VS2013 doesn't support C++ 11, then we don't support VS2013. Given that VS2015 supports it, and that's four years old, I'm comfortable closing this.

**Comment by adrian-bodenmann** [comment]
I commented-out PROJECT_LABEL from CMakeLists.txt and created a pull request (#776). 

With this it compiles in VS2015 and VS2017. (Under VS2017 some of the projects fail to build, but the yaml-cpp library file is generated). 
I agree that at this stage dropping support for VS2013 makes sense.
