### ISSUE TITLE
Linker error with Visual Studio 2015

### ISSUE THREAD

**Issue by adrian-bodenmann** [jbeder/yaml-cpp#767]
Since commit 5e9cb01 on 27 September, the project doesn't compile on Visual Studio 2015 (64bit, Win10).
Error:
LINK : fatal error LNK1181: cannot open input file '..\Release\yaml-cpp.lib'

**Comment by pvaddina** [comment]
This may be related to the problem-1, I described in #766. I believe what is happening here is the library (yaml-cpp) not compiling and as a result the rest of the projects which link against it fail with this error. An easy work around is to simply remove the PROJECT_LABEL property in the CMakeLists.txt.

**Comment by jbeder** [comment]
I'll dupe this to #766, but let me know if you feel it's different, and I'll reopen.
