### ISSUE TITLE
Clarification: underscores in numbers

### ISSUE THREAD

**Issue by david-mohr** [jbeder/yaml-cpp#781]
I can't seem to find a definitive answer if this is a bug or not. The 1.1 Spec explicitly allows underscores in numbers, and blocking them in 1.2 would break compatibility.

So I'm here to simply request a clarification on your view of the spec.

Thank you.

```
#include <yaml-cpp/yaml.h>

int main() {
  YAML::Node number = YAML::Load("number: 10_1");
  int blah = number["number"].as<int>();
}
```
Results:
```
terminate called after throwing an instance of 'YAML::TypedBadConversion<int>'
  what():  yaml-cpp: error at line 1, column 9: bad conversion
```

**Comment by jbeder** [comment]
Check out tag resolution in the 1.2 spec:

https://yaml.org/spec/1.2/2009-07-21/spec.html#id2604185

[-+]? [0-9]+	 tag:yaml.org,2002:int (Base 10)
[-+]? ( \. [0-9]+ | [0-9]+ ( \. [0-9]* )? ) ( [eE] [-+]? [0-9]+ )?	 tag:yaml.org,2002:float (Number)

Looks like in either case, underscores are not allowed.
