### ISSUE TITLE
Does yaml-cpp support enumeration type?

### ISSUE THREAD

**Issue by JiayiFu** [jbeder/yaml-cpp#784]
Hi, 
  I want to know whether enumeration was supported by yaml-cpp. I tried to search the keyword 'enum' in the repo but didn't find too much info.
  Thanks!

**Comment by jbeder** [comment]
What do you mean, enumeration? What are you trying to do?

**Comment by JiayiFu** [comment]
In fact, I still have not completely know what I want to do...
