### ISSUE TITLE
Cannot be used as bazel lib: BUILD file not found in directory

### ISSUE THREAD

**Issue by sammi** [jbeder/yaml-cpp#785]
When add bazel lib reference in my repo like:
```
http_archive(
    name = "com_github_jbeder_yaml_cpp",
    sha256 = "77ea1b90b3718aa0c324207cb29418f5bced2354c2e483a9523d98c3460af1ed",
    strip_prefix = "yaml-cpp-yaml-cpp-0.6.3",
    urls = [
        "https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.3.tar.gz",
    ],
)
```

And then run ```bazel build ...```

I got errors:
```
C:\Users\songy\tuware>bazel build ...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to 'C:/users/songy/_bazel_songy/n435ocyg/command.profile.gz'
ERROR: C:/users/songy/tuware/cluster/BUILD:8:1: no such package '@com_github_jbeder_yaml_cpp//': BUILD file not found in directory '' of external repository @com_github_jbeder_yaml_cpp. Add a BUILD file to a directory to mark it as a package. and referenced by '//cluster:cluster_test'
ERROR: Analysis of target '//cluster:cluster_test' failed; build aborted: no such package '@com_github_jbeder_yaml_cpp//': BUILD file not found in directory '' of external repository @com_github_jbeder_yaml_cpp. Add a BUILD file to a directory to mark it as a package.
INFO: Elapsed time: 12.647s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (15 packages loaded, 59 targets configured)
```

When I check the release source code: https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.3.tar.gz,  the build file is not included.

![image](https://user-images.githubusercontent.com/189128/68448693-288a5580-0199-11ea-825b-fbb1d8de3874.png)

**Comment by tt4g** [comment]
`BUILD.bazel` was added after yaml-cpp 0.6.3.

**Comment by sammi** [comment]
Can we do a new release from current master to include BUILD.bazel?

**Comment by tt4g** [comment]
I have never used Bazel.

I found `git_repository` in the documentation but that is deprecated (`load(..., "git_repository")` is recommended).

* https://docs.bazel.build/versions/0.19.1/be/workspace.html#git_repository

**Comment by sammi** [comment]
git_repository is not the best practice, we use http_archive by default.

It's pretty easy to do that, just need create a new release from master. I've made it work in my forked version already, no source change are needed.  Here is the working version for me, it would be nice if could make it work in yaml-cpp repo.



```http_archive(
    name = "com_github_jbeder_yaml_cpp",
    sha256 = "1df36d25ff796a79bee69ea42ee2b86be09ac9f3582efaf5a26037f09033297b",
    strip_prefix = "yaml-cpp-yaml-cpp-0.6.4",
    urls = [
        "https://github.com/sammi/yaml-cpp/archive/yaml-cpp-0.6.4.tar.gz",
    ],
)```

**Comment by jbeder** [comment]
Yes, we will do a new release, but there are some bugs introduced in the CMake files that need to be resolved first. Probably pinning to a version like git_repository is best for the time being.
