### ISSUE TITLE
newer version changed bool auto conversion

### ISSUE THREAD

**Issue by seisowl** [jbeder/yaml-cpp#822]
Old version was able to convert Node to bool, but new version broke this.
In addition, I am confused by IsNull() and IsDefined() ... See the output of the program.

Code:
```
// g++ -g -std=c++11 -c main.cpp
// g++ main.o -lyaml-cpp -o test

#include <iostream>
#include <yaml-cpp/yaml.h>
using YAML::Node;

void func_requires_bool(bool b) {
  std::cout << b << std::endl;
}

int main(int argc, char** argv) {
  Node yml;

  yml["a"] = 1;

  // func_requires_bool(yml["b"]);             // won't compile in newest version, did compile in old version
  func_requires_bool(yml["b"].IsDefined()); // 0
  func_requires_bool(!yml["b"].IsNull());   // 1 (surprise?) 
  
  return 0;
}
```
Compiler error when uncomment line 17:
> main.cpp: In function ‘int main(int, char**)’:
> main.cpp:17:30: error: cannot convert ‘YAML::Node’ to ‘bool’ for argument ‘1’ to ‘void func_requires_bool(bool)’
>    func_requires_bool(yml["b"]);             // won't compile

**Comment by Dekken** [comment]
the operator was made explicit, so you must static_cast it or do something like 

```
func_requires_bool(bool{yml["b"]}); 
```

**Comment by dota17** [comment]
```
  func_requires_bool(yml["b"].IsDefined()); // 0
  func_requires_bool(!yml["b"].IsNull());   // 1 (surprise?) 
```
@seisowl  It looks like normal. You can see the code:
https://github.com/jbeder/yaml-cpp/blob/33316d531bd9032d66f5bcc3ba1fd114a4ab0e1c/include/yaml-cpp/node/node.h#L55

https://github.com/jbeder/yaml-cpp/blob/33316d531bd9032d66f5bcc3ba1fd114a4ab0e1c/include/yaml-cpp/node/detail/node_data.h#L47

because the `yml["b"]` is not defined, the `type()` returns `NodeType::Undefined`.

**Comment by jbeder** [comment]
Yep, this is intentional. You can still use it without a cast in boolean contexts, e.g.:

```
if (yml["b"]) {
 // do something
}
```
