### ISSUE TITLE
ambiguous call to overloaded function - Windows VS 2019 (latest)

### ISSUE THREAD

**Issue by Dekken** [jbeder/yaml-cpp#823]
```
p\\include\yaml-cpp/node/convert.h(161): note: while trying to match the argument list '(const unsigned __int64)'
p\\include\yaml-cpp/node/convert.h(163): error C2668: 'signbit': ambiguous call to overloaded function
C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\corecrt_math.h(305): note: could be 'bool signbit(float) throw()'
C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\corecrt_math.h(310): note: or       'bool signbit(double) throw()'
C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\corecrt_math.h(315): note: or       'bool signbit(long double) throw()'

**Comment by Dekken** [comment]
from: https://github.com/jbeder/yaml-cpp/pull/817

**Comment by msuiche** [comment]
Yes. I do have the same problem here too.

**Comment by TedLyngmo** [comment]
Reproducible example: https://godbolt.org/z/HQmy3y
Have you filed a bug report on MSVC?
It's supposed to do `std:.signbit(static_cast<double>(IntArg))` in these cases.

**Comment by barcharcraz** [comment]
this isn't a quick fix, because we're not sure if the standard's mandate of integer overloads for the floating point related functions in cmath is intended.

I would strongly suggest not calling those overloads in libyaml

**Comment by nihalar** [comment]
> this isn't a quick fix, because we're not sure if the standard's mandate of integer overloads for the floating point related functions in cmath is intended.
> 
> I would strongly suggest not calling those overloads in libyaml

How to fix it? I am facing the same problem.

**Comment by TedLyngmo** [comment]
@barcharcraz The intent of paragraph [[`cmath.syn/2`]](https://eel.is/c++draft/cmath.syn#2) in the C++20 draft and in the C++17 standard seems pretty clear to me, but I see that the issue I raised is now tagged `LWG` so I suppose you'll propose a change in the upcoming standard to be applied backwards to affect C++17 too.

My "_quick fix(™)_" remark was meant to acknowledge that it may require more work than I anticipate to get this done even though it looks fairly straightforward.

**Comment by nihalar** [comment]
> @barcharcraz The intent of paragraph [[`cmath.syn/2`]](https://eel.is/c++draft/cmath.syn#2) in the C++20 draft and in the C++17 standard seems pretty clear to me, but I see that the issue I raised is now tagged `LWG` so I suppose you'll propose a change in the upcoming standard to be applied backwards to affect C++17 too.
> 
> My "_quick fix(™)_" remark was meant to acknowledge that it may require more work than I anticipate to get this done even though it looks fairly straightforward.

What should a developer who needs to use it urgently do?

**Comment by Dekken** [comment]
the fix is here https://github.com/jbeder/yaml-cpp/pull/824

**Comment by Dekken** [comment]
with PR #824 merged, this can be closed, or leave open to track changes in MSVC
