### ISSUE TITLE
read me has error

### ISSUE THREAD

**Issue by liguangcheng** [jbeder/yaml-cpp#832]
cmake [-G generator] [-DYAML_BUILD_SHARED_LIBS=ON|OFF] ..

yaml-cpp has no YAML_BUILD_SHARED_LIBS attribute, please update

**Comment by Dekken** [comment]
```
https://github.com/jbeder/yaml-cpp/search?q=YAML_BUILD_SHARED_LIBS&unscoped_q=YAML_BUILD_SHARED_LIBS
```

it seems to have something like that

**Comment by jbeder** [comment]
Agreed. What error are you getting?

**Comment by teyrana** [comment]
This seems fixed.  (I'm currently building with `-DYAML_BUILD_SHARED_LIBS=ON`)
