### ISSUE TITLE
Emitt yaml with secondary handle ("!!") for custom types.

### ISSUE THREAD

**Issue by Jerry-Ma** [jbeder/yaml-cpp#838]
Hi,

I am trying to emit yaml of the following content but without success:

```
# ---
# datatype:
# - {name: value, datatype: float64}
# meta: !!omap
# - {meta1: value1}
# - {meta2: 3}
```

The part that I am not able to get right is the ``!!omap`` custom type tag. I am using `Node::SetTag("omap")` to set the tag, however, that result in `!<omap>`. I searched the repo and found there is a `Tag::Translate` method defined with multiple kind of tags including `!!` but I guess this is not used in the emitting but just for reading. Any suggestions?

**Comment by perlpunk** [comment]
I'm not an expert on yaml-cpp, but try out setting `tag:yaml.org,2002:omap` instead. All the standard `!!int`, `!!map` etc. tags are just shortcuts for `tag:yaml.org,2002:...`

**Comment by Jerry-Ma** [comment]
Thank you very much, this indeed works great!

**Comment by Jerry-Ma** [comment]
I am closing this issue for now.
