### ISSUE TITLE
LoadFile only reads up to first paragraph separator line ("---")

### ISSUE THREAD

**Issue by dlobron** [jbeder/yaml-cpp#852]
When calling YAML::LoadFile on a YAML file with paragraph separators, I find that I only get a single YAML::Node, representing the text up to the separator.  For example, consider this YAML:
```
foo:
  bar1: 1
  bar2: 2
  bar3: 3
---
foo2:
  bar4: 4
---
foo3:
  bar5:
    - baz: 5
```
When I read this in with YAML::LoadFile, I get `YAML::Nodes` only up to the first separator (each of these statements is printed after checking the node's type with `GetType()`:
```
DBG: converting node of type map
DBG: converting node of type map
DBG: converting node of type scalar
DBG: converting node of type scalar
DBG: converting node of type scalar
```
But when I remove the separators, I get the full list:
```
DBG: converting node of type map
DBG: converting node of type map
DBG: converting node of type scalar
DBG: converting node of type scalar
DBG: converting node of type scalar
DBG: converting node of type seq
DBG: converting node of type scalar
DBG: converting node of type map
DBG: converting node of type map
DBG: converting node of type scalar
```
I'm writing the file following the steps in the tutorial (https://github.com/jbeder/yaml-cpp/wiki/How-To-Emit-YAML).

**Comment by dota17** [comment]
You can use API LoadAllFromFile() to load a YAML file with paragraph separators. Reference as follows:
```cpp
int main()
{
    YAML::Emitter out;
    std::vector<YAML::Node> docs = YAML::LoadAllFromFile("./config.yaml");
    out << docs;
    printf("str: \n %s", out.c_str());
    return 0;
}
```
