### ISSUE TITLE
Negative integer can be decoded as unsigned

### ISSUE THREAD

**Issue by StefanFabian** [jbeder/yaml-cpp#859]
I've made the apparently wrong assumption that `node.as<unsigned long long>()` would throw a `YAML::BadConversion` exception if the number is negative.
In reality a value like:
```
int16s:
  - -15850
```
will be converted to 18446744073709535766.
In #209, it is argued that bool Nodes should not have an implicit conversion to int (which I support since they are semantically different types), hence, I assume that yaml not throwing in the above case is not intended?

**Comment by jbeder** [comment]
Sure, that's probably not intended. I'll accept a PR to fix.

**Comment by dota17** [comment]
Fixed by #861
