### ISSUE TITLE
LoadFile should take a std::filesystem::path instead of std::string

### ISSUE THREAD

**Issue by Lawrencemm** [jbeder/yaml-cpp#866]
Given `std::string` is implicitly convertible to `std::filesystem::path` this shouldn't break any existing valid code.

It just makes it nicer to use the API when I'm using the std filesystem API.

Please note, `std::filesystem::path` is not implicitly convertible to `std::string` on all platforms, see here: https://stackoverflow.com/questions/57377349/implicit-conversion-between-stdfilesystempath-and-stdstring-should-it-hap

Edit: I forgot std::filesystem is C++17, any ideas on a good to for updating the minimum standard?

**Comment by jbeder** [comment]
I'm happy to require C++17 for something particularly important, but this doesn't seem crucial. Definitely open to it in the future, once C++17 is required.

Probably would want an overload rather than changing the existing function.
