### ISSUE TITLE
Appending file without loading all its content to memory

### ISSUE THREAD

**Issue by Kyeiv** [jbeder/yaml-cpp#874]
Hello i am wondering if there is another way to append a yaml file. for now only solution that comes into my mind is Yaml::Load a file to Node object, add some data to it and then emmit it, but it requires loading all the data to memory, is there a more elegant solution?

**Comment by jbeder** [comment]
I suppose you could just open the file in append mode, and write more data. But you wouldn’t know if the whole file is valid YAML or not.
