### ISSUE TITLE
Arbitrary depth search?

### ISSUE THREAD

**Issue by gguyver** [jbeder/yaml-cpp#898]
Is it possible to search the YAML tree by providing a single array/vector of keys?

For example:
```cpp
std::vector<std::string> keys{{"key1", "key2", "key3"}};
YAML::Node = already_extant_yaml[keys];
```

Such that the example would be equivalent to `already_extant_yaml["key1']["key2"]["key3"]`.

If so, it would great if that could be added to the Tutorial. If not, would it be something you'd be willing to add?

**Comment by jbeder** [comment]
That’s not supported, and couldn’t be, since YAML allows arbitrary keys; in particular, you could have a key that’s a vector of strings, and there’d be no way to distinguish that from your syntax above.
