### ISSUE TITLE
Hang in parser

### ISSUE THREAD

**Issue by fuzzah** [jbeder/yaml-cpp#899]
Hi.
This simple string (file) results in hang in utils/parse: `[:]`
as well as this one: `{:]`
To reproduce one can use:
```
echo "[:]" | ./parse
```
 
This is as of 5a9ab177bad9665ac5eb8f5b12435052123b5b6f

**Comment by dota17** [comment]
This problem is similar to #740, I'm trying to fix it.

**Comment by jbeder** [comment]
Fixed by #911.
