### ISSUE TITLE
List of Objects, List of Lists

### ISSUE THREAD

**Issue by GitShard** [jbeder/yaml-cpp#914]
Hey guys,

Any reason why this markup is not supported in v0.6.3 (list of dictionary)?
[Dash+Space]
[Indent]Key_0: Val_0
[Indent]Key_1: Val_1
[Indent]Key_2: Val_2
[Indent]Key_3: Val_3
[Indent]Key_4: Val_4

Presumably the following would work, but the former should not raise exception should it?
[Indent+Dash+Space]Key_0: Val_0
[____Extended Indent]Key_1: Val_1
[____Extended Indent]Key_2: Val_2
[____Extended Indent]Key_3: Val_3
[____Extended Indent]Key_4: Val_4

Al
P.S. [Dash] means - (but markdown makes it a bit difficult)

**Comment by jbeder** [comment]
You can use triple-back quotes to display code. Or press the “code” button in github.

Please post the code you’re using to parse the yaml as well, along with what you expect to happen and what actually happens.

**Comment by GitShard** [comment]
The picture shows the run result with the throw for the indented and the success of the compact.
![yaml-cpp-run](https://user-images.githubusercontent.com/67800082/86509889-9ac83e00-bdeb-11ea-85ed-7c57489db146.png)

Here is the code. The error printing function is not included.
```
std::string makeYamlString() {
    std::string result = "- \n";
	
    result += "\tKey_0: Val_0\n";
    result += "\tKey_1: Val_1\n";
    result += "\tKey_2: Val_2\n";
    result += "\tKey_3: Val_3\n";
    result += "\tKey_4: Val_4\n";
	
    return result;
}

std::string makeYamlCompactString() {
    std::string result = "- Key_0: Val_0\n";
    
    result += "  Key_1: Val_1\n";
    result += "  Key_2: Val_2\n";
    result += "  Key_3: Val_3\n";
    result += "  Key_4: Val_4\n";
	
    return result;
}

int main (int argc, char** argv) {
    try {
        std::string desired = makeYamlString();
        
        std::cout << "DESIRED:"
                       << std::endl
                       << desired 
                       << std::endl;
		
        auto node = YAML::Load(desired);
		
        std::cout << "SUCCESS!" << std::endl;
    }
    catch (YAML::ParserException ex) {
        printError(ex.mark, ex.msg);
    }
	
    try {
        std::string compact = makeYamlCompactString();
		
        std::cout << "COMPACT:"
                       << std::endl 
                       << compact 
                       << std::endl;		
		
         auto node = YAML::Load(compact);
		
         std::cout << "SUCCESS!" << std::endl;
    }
    catch (YAML::ParserException ex) {
        printError(ex.mark, ex.msg);
    }
	
    return 0;
}

**Comment by dota17** [comment]
The [yaml spec](https://yaml.org/spec/1.2/spec.html#id2777534) says in chapter 6:

  `To maintain portability, tab characters must not be used in indentation, since different systems treat tabs differently.`

so we shouldn't use tab characters in indentation.

**Comment by GitShard** [comment]
Life saver, thank you! 
I tried the previous code with spaces and it worked for both list of object and list of list (in v0.6.3).
