### ISSUE TITLE
Not stripping whitespace after block scalars in map

### ISSUE THREAD

**Issue by rjk9w5** [jbeder/yaml-cpp#917]
Adding this test to specexamples:
`const char* exRyan = "key: value\t \t#Comment\n";`

Found the value comparison fails:
`EXPECT_EQ("value", doc["key"].as<std::string>());`

Where the return of `as<string>` is "value\t"

This should have stripped the white space after value, but it does not.

**Comment by rjk9w5** [comment]
Interestingly, when ex6_4 is modified to include \t after the line it does not fail.

Adding a `\t#asdf` after "text" in ex6_4 results in a parsing error

Adding `\t #asdf` also leads to the same parsing error

Adding ` #asdf` also leads to the same parsing error

I have tried looking through the spec and I don't believe that trailing white space should be stripped from these with the comment. I also think that continued lines such as in ex6_4 should permit a comment line in between the values.

I am looking into this now. I will post updates as I have them.

**Comment by rjk9w5** [comment]
Note, just putting a tab or space is fine. The issue arises when there is also a comment after the tab.

**Comment by dota17** [comment]
> const char* exRyan = "key: value\t \t#Comment\n"

I think it is a bug and the `\t` after the `value` should be removed during parsing.

> Adding a \t#asdf after "text" in ex6_4 results in a parsing error
Adding \t #asdf also leads to the same parsing error
Adding #asdf also leads to the same parsing error

But these three are the wrong examples and we should not do these.
