### ISSUE TITLE
Yaml::Load stalls and segfaults on specific string input

### ISSUE THREAD

**Issue by MarkOates** [jbeder/yaml-cpp#938]
I seem to have found an input string that causes `YAML::Load` to freeze program execution.

```cpp
#include <yaml-cpp/yaml.h>

int main(int, char**)
{
   std::string invalid_source_yaml = "{# ke\ny{:";       // magic broke-ya string
   YAML::Node node = YAML::Load(invalid_source_yaml);
   return 0;
}
```

I don't know enough about the parser to dig deeper or know if I should check for valid parsing before calling `YAML::Load`.

Regardless, I'm using homebrew version version `yaml-cpp (0.6.2_1)`.

**Comment by MarkOates** [comment]
I've upgraded to `yaml-cpp 0.6.3_1` which is the latest available version off of homebrew and still experience this parsing failure.

**Comment by dota17** [comment]
I think `"{# ke\ny{:"` which leads the `core dump` is not a special string. This is a wrong yaml file.  What do you focus on about this question.

**Comment by MarkOates** [comment]
> This is a wrong yaml file.

`YAML::Load` does not load a file, but rather it loads a `std::string` containing yaml markup.

**Comment by dota17** [comment]
> This is a wrong yaml file.

My fault. this expression is not clear. I mean that this yaml string's format is not correct and yaml-cpp will throw an exception when load this. Do you mean this is a bug or it should not throw an exception here?

**Comment by MarkOates** [comment]
> Do you mean this is a bug or it should not throw an exception here?

The problem is that it is _not_ throwing an exception.  The program execution is freezing.  Rather, I would expect an exception to be thrown (probably an [`invalid_argument`](http://www.cplusplus.com/reference/stdexcept/invalid_argument/))  with a message indicating that there is a parsing error.

**Comment by jbeder** [comment]
Can you try this at HEAD? There have been some fixes to parsing that haven't been released yet.

**Comment by dota17** [comment]
@MarkOates 
ha, I try this in version 0.6.3 and I am quite familiar with this question. I have fixed this bug in #911. Please let me know if there are any other question.

**Comment by MarkOates** [comment]
> Can you try this at HEAD? There have been some fixes to parsing that haven't been released yet.

```
libc++abi.dylib: terminating with uncaught exception of type YAML::ParserException: yaml-cpp: error at line 2, column 3: unknown token
zsh: abort      bin/programs/rudimentary_yaml_crashing_example
```
^^ new program output

Awesome!! 😍🎉. Snappy execution!

Thank you @jbeder, and @dota17 your support as well.

Have you guys considered submitting the `yaml-cpp` project to the [GitHub Sponsors](https://github.com/sponsors) program?  I'd love to donate.  I use calls to this library probably 100s of times per day, to be honest.

**Comment by MarkOates** [comment]
I'll close this issue because it has resolved. 👍
