### ISSUE TITLE
Including yaml. header in 64-bit VS project generates compiler warning C4244

### ISSUE THREAD

**Issue by jmo-gelsight** [jbeder/yaml-cpp#940]
I am trying to use the latest yaml-cpp (pulled yesterday) in a a VS 2019 project (64-bit build).  But when I just add a single #include statement with the basic header

`#include "yaml-cpp/yaml.h"`

 ...it generates a C4244 warning that prevents my project from building (see text of warnings below).  This forces me to disable that warning.  I can do that but it would be nice to try to address the cause.  Unfortunately I am unable to determine what the cause is.  

Obviously its warning about converrting "int" to "signed char" but who is trying to do that and where?  It's not me.  This happens without me adding any yaml-cpp-specific code at all

This is admittedly pretty minor.  I just figured someone should mention it.  I'd love to try to fix it myself but I don't know where to begin.  Should I just add a static cast there?  Is that something the author would approve of?  What if the number read-in is negative but type T is an unsigned type?

```
2>C:\Users\jmole\Documents\Dev\ThirdParty\yaml-cpp\include\yaml-cpp\node\convert.h(130,13): error C2220: the following warning is treated as an error
2>C:\Users\jmole\Documents\Dev\ThirdParty\yaml-cpp\include\yaml-cpp\node\convert.h(209): message : see reference to function template instantiation 'bool YAML::conversion::ConvertStreamTo<signed char>(std::stringstream &,T &)' being compiled
2>        with
2>        [
2>            T=signed char
2>        ]
2>C:\Users\jmole\Documents\Dev\ThirdParty\yaml-cpp\include\yaml-cpp\node\convert.h(130,13): warning C4244: '=': conversion from 'int' to 'T', possible loss of data
2>        with
2>        [
2>            T=signed char
2>        ]
2>C:\Users\jmole\Documents\Dev\ThirdParty\yaml-cpp\include\yaml-cpp\node\convert.h(130,13): warning C4244: '=': conversion from 'int' to 'T', possible loss of data
2>        with
2>        [
2>            T=unsigned char
2>        ]
2>C:\Users\jmole\Documents\Dev\ThirdParty\yaml-cpp\include\yaml-cpp\node\convert.h(210): message : see reference to function template instantiation 'bool YAML::conversion::ConvertStreamTo<unsigned char>(std::stringstream &,T &)' being compiled
2>        with
2>        [
2>            T=unsigned char
2>        ]
2>Generating Code...
2>Done building project "gscoretests_v16.vcxproj" -- FAILED.
StopOnFirstBuildError: Build cancelled because project "gscoretests_v16" failed to build.
```

**Comment by jbeder** [comment]
Happy to accept a PR, but I'm going to close this issue since it's just a warning.

**Comment by jmo-gelsight** [comment]
That's great.  I'll be happy to try to do the change and PR but what do you think should be done?  Just cast? the value  And if that is what you think should be done, what should the code do if the type is unsigned and the value read in is signed?

**Comment by jbeder** [comment]
I’m sorry, I haven’t really thought it through. Probably a cast isn’t
right, but I’m not sure.
