### ISSUE TITLE
cant find_package()

### ISSUE THREAD

**Issue by yairBAR-caja** [jbeder/yaml-cpp#951]
Hi,
I installed your very nice library.
cant use it in my project though.. 
find_package() cannot find "yaml-cpp::yaml-cpp" which is the alias set in the cmake.
so i tried uninstalling, but theres no uninstall rule.

:(

**Comment by yairBAR-caja** [comment]
ok my mistake, i did not install the latest release.

after installing latest release I added to my cmake:
set ( CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} path/to/buid_dir) 
find_package(yaml-cpp REQUIRED)

and it works.

**Comment by Akaame** [comment]
@yairBAR-caja @jbeder Could you please close this?

**Comment by yairBAR-caja** [comment]
yea of-course my horse
