### ISSUE TITLE
Auto conversion of node type

### ISSUE THREAD

**Issue by ajaykkv** [jbeder/yaml-cpp#965]
Hi,

I am using yaml-cpp-0.6.2 in my project and i see that yaml-cpp is automatically coverting type of node value. For example,

mode: off

when I read "mode" value as string, I get value "False". Is there any way to avoid such auto coversion?

/kkv

**Comment by jbeder** [comment]
This is surprising. Can you post some code?

**Comment by ajaykkv** [comment]
It seems the python wrapper used for yaml-cpp is causing this issue. This is not a yaml-cpp issue. Thanks!
