### ISSUE TITLE
Add single quote to string in a sequence

### ISSUE THREAD

**Issue by pango99** [jbeder/yaml-cpp#974]
Hi:
   `

      YAML::Node yaml_node;
       yaml_node["names"].push_back("BENZ");
	yaml_node["names"].push_back("bmw");
	yaml_node["names"].push_back("tesla");
	yaml_node["names"].SetStyle(YAML::EmitterStyle::Flow);
`
We know,above code can generate YAML text "names: [BENZ, bmw, tesla]",but how to add single quote to every string in the sequence just like "names: ['BENZ', 'bmw', 'tesla']"?

**Comment by jbeder** [comment]
YAML::SingleQuoted

**Comment by pango99** [comment]
> 
> 
> YAML::SingleQuoted

What the meaning? How do I use the constant?

**Comment by jbeder** [comment]
https://github.com/jbeder/yaml-cpp/wiki/How-To-Emit-YAML#using-manipulators
