### ISSUE TITLE
How can I implement automatic type conversion?

### ISSUE THREAD

**Issue by xenonz95** [jbeder/yaml-cpp#983]
I want to assign values to variables like using python, But when I overload the string type conversion operator, a problem that I can't solve appears.

I use the following simple code for type conversion：（in class Node in include/yaml-cpp/node/node.h ）
```C++
template <class T>
operator T() {
  return (*this).as<T>();
}
```
It works well with basic types such as int and double.
But there is a magical problem when converting to string:
```C++
int i = yaml-Node["key"]; // is OK
i = yaml-Node["key"]; // is OK
string s = yaml-Node["key"]; // is also OK
s = yaml-Node["key"]; //Compile Error, Type conversion is ambiguous
```
I tried some methods, but none of them worked

**Comment by jbeder** [comment]
This is why there's the 'as' function :)

**Comment by xenonz95** [comment]
I want to omit the 'as' function
Just that the string doesn't work well
