### ISSUE TITLE
Crash when Creating a Map in the Unreal Engine

### ISSUE THREAD

**Issue by jwindgassen** [jbeder/yaml-cpp#987]
Hey there.

I'm trying to use yaml-cpp in combination with the Unreal Engine. I am currently trying to create a Node as a map, but the Editor crashes for some weird reason when I execute that Code.

Here is a mwe that I'm trying to execute (basically the beginning of one of the Tutorials):
```
void UMyLibrary::TestFunction() {
	YAML::Node node;
	node["string"] = "TestString123";
}
```

As soon as I run this function the editor crashed without a bug report, so unfortunately I don't have a lot of debugging information:
 - I currently use Rider from JetBrains as the IDE, but the same crash happened with Visual Studio
 - When I run the code in Debug-Mode and step through this code manually, there is no error.
 - If I replace `node["string"] = "TestString123"` with `node = "TestString123"` the code runs fine, so I think the `[]`-Operator is the cause of the Crash
 - Therefore: Running `YAML::Node = node["string"]` also crashed the Program.

I tried assigning Key and Value beforehand to a separate variable on type `std::string`, but that doesn't solve the issue.

I don't know if you guys have a lot of experience with the Unreal Engine, but maybe you can help me anyway.

~Okaghana

**Comment by jwindgassen** [comment]
I tested a little bit more: Using `node["string"] = std::string(TCHAR_TO_UTF8("TestString123"));` works. `TCHAR_TO_UTF8` converts the internal Unreal Strings to normal c++ strings. But e.g. when I want to use a Float instead of a String, I still don't have a way to add that to a Node as the method above only works with strings.

**Comment by Akaame** [comment]
Hello,

What is an internal Unreal String?
`TCHAR_TO_UTF8` just changes the encoding of given char array.
So your code is not much different than
`node["string"] = std::string("ABC");`

> Therefore: Running YAML::Node = node["string"] also crashed the Program.

`YAML::Node = node["string"] `, this is by no means valid C++.

A basic example with a crash at end.

```cpp
#include "yaml-cpp/yaml.h"
#include <iostream>

int main() {
    YAML::Node node;
    node["string"] = "TestString123"; // Node is now: string: TestString123
    node["abc"] = 17.5;
    node[17.5] = "string";
    std::cout << node["string"]  << std::endl; // TestString123
    std::cout << node << std::endl; 
    // string: TestString123
    // abc: 17.5
    // 17.5: string
   node = "TestString123";
    std::cout << node << std::endl; // TestString123
    std::cout << node["string"] << std::endl; // string is not a valid key anymore So:
    // libc++abi: terminating with uncaught exception of type YAML::BadSubscript: operator[] call on a scalar (key: "string")
    // Abort trap: 6
    return 0;
}
```

Sharing your error dump would be the most helpful in this situation if you are still facing this issue.

Regards.
