### ISSUE TITLE
Build failure due to stricter `-Werror` in `g++`

### ISSUE THREAD

**Issue by YesserLab** [jbeder/yaml-cpp#996]
Building the library (commit 98acc5a8874faab28b82c28936f4b400b389f5d6) on ArchLinux with `g++ 11.1.0` causes the following error:

```
[ 55%] Building CXX object test/prefix/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from ***/yaml-cpp/test/gtest-1.10.0/googletest/src/gtest-all.cc:42:
***/yaml-cpp/test/gtest-1.10.0/googletest/src/gtest-death-test.cc: In function ‘bool testing::internal::StackGrowsDown()’:
***/yaml-cpp/test/gtest-1.10.0/googletest/src/gtest-death-test.cc:1301:24: error: ‘dummy’ may be used uninitialized [-Werror=maybe-uninitialized]
1301 |   StackLowerThanAddress(&dummy, &result);
***/yaml-cpp/test/gtest-1.10.0/googletest/src/gtest-death-test.cc:1290:13: note: by argument 1 of type ‘const void*’ to ‘void testing::internal::StackLowerThanAddress(const void*, bool*)’ declared here
1290 | static void StackLowerThanAddress(const void* ptr, bool* result) {
     |             ^~~~~~~~~~~~~~~~~~~~~
***/yaml-cpp/test/gtest-1.10.0/googletest/src/gtest-death-test.cc:1299:7: note: ‘dummy’ declared here
1299 |   int dummy;
     |       ^~~~~
```

**Comment by jbeder** [comment]
Looks like a warning?

**Comment by YesserLab** [comment]
Yes indeed. But the tests are compiled with `-Werror`
As you can see in the error message:
`[-Werror=maybe-uninitialized]`

**Comment by jbeder** [comment]
yaml-cpp doesn't make undue effort to eliminate warnings. I'll accept PRs that are reasonable code that happen to eliminate warnings, though.

**Comment by Max-Rodriguez** [comment]
Having this issue months after this PR.
Also on Arch Linux, with g++ 11.

I grepped "-Werror" on the Makefile created by CMake, but there is no found matches, so I have no idea what part of the makefile it gives the compiler this flag to count warnings as errors.

**Comment by KitsuneRal** [comment]
FWIW, `-Werror` is added in `test/gtest-1.10.0/googletest/cmake/internal_utils.cmake` and is only used when building GTest code. https://github.com/google/googletest/pull/3024 fixes that.

**Comment by Max-Rodriguez** [comment]
> FWIW, `-Werror` is added in `test/gtest-1.10.0/googletest/cmake/internal_utils.cmake` and is only used when building GTest code. [google/googletest#3024](https://github.com/google/googletest/pull/3024) fixes that.

Thanks! This worked.

**Comment by paradajz** [comment]
Another workaround:

`cmake -DYAML_CPP_BUILD_TESTS=OFF ..`
